SET CCC(CCCRRRAAA)  'All Countries'
/                                  
NORWAY                             
DENMARK                            
FINLAND                            
GERMANY                            
NETHERLANDS                        
SWEDEN                             
UNITED_KINGDOM                     
ESTONIA                            
LATVIA                             
LITHUANIA                          
POLAND                             
/;                                 
