SET CCCRRR(CCC,RRR) "Regions in countries"                         
/                                                                  
DENMARK                                                .    DK2    
DENMARK                                                .    DK1    
FINLAND                                                .    FIN    
GERMANY                                                .    DE4-E  
GERMANY                                                .    DE4-N  
GERMANY                                                .    DE4-S  
GERMANY                                                .    DE4-W  
NETHERLANDS                                            .    NL     
ESTONIA                                                .    EE     
LATVIA                                                 .    LV     
LITHUANIA                                              .    LT     
POLAND                                                 .    PL     
NORWAY                                                 .    NO1    
NORWAY                                                 .    NO2    
NORWAY                                                 .    NO3    
NORWAY                                                 .    NO4    
NORWAY                                                 .    NO5    
SWEDEN                                                 .    SE1    
SWEDEN                                                 .    SE2    
SWEDEN                                                 .    SE3    
SWEDEN                                                 .    SE4    
UNITED_KINGDOM                                         .    UK     
/;                                                                 
