SET DEF_U3(DEF) 'Upwards steps in elastic el. demand, absolute Money and fraction of nominal demand data format'
/                                                                                                               
* Commerce_U3, Industry_U3, Residential_U3, Agriculture_U3,  PublicServ_U3,  ProcessingInd_U3                   
* DEF_D3_3,DEF_D3_2,DEF_D3_1                                                                                    
/;                                                                                                              
