SET DEF_U2(DEF) 'Upwards steps in elastic el. demand, absolute Money and MW-incremental data format'
/                                                                                                   
* Empty, i.e. no elasticity in demand from DEF_U2                                                   
/;                                                                                                  
