SET DEF_D3(DEF) 'Downwards steps in elastic el. demand, absolute Money and fraction of nominal demand data format'
/                                                                                                                 
*Commerce, Industry, Residential, Agriculture,  PublicServ,  ProcessingInd                                        
*  DEF_D3_3,DEF_D3_2,DEF_D3_1                                                                                     
/;                                                                                                                
