SET DEF_D2(DEF) 'Downwards steps in elastic el. demand, absolute Money and MW-incremental data format'
/                                                                                                     
* Empty, i.e. no elasticity in demand from DEF_D2                                                     
/;                                                                                                    
