$ifi not %FSS%==yes $goto FSS_var2001_label1
TABLE DEF_STEPS2
                                 DEF_D3_3   DEF_D3_2  DEF_D3_1

2005.DK_E.S01.T001.DF_QUANT         8.2        0          0
2005.DK_W.S01.T001.DF_QUANT         11.8       0          0
2005.FI_R.S01.T001.DF_QUANT         400        0          0
2005.NO_N.S01.T001.DF_QUANT         192        0          0
2005.NO_M.S01.T001.DF_QUANT         192        0          0
2005.NO_S.S01.T001.DF_QUANT         848        0          0
2005.NO_O.S01.T001.DF_QUANT         368        0          0
2005.SE_N.S01.T001.DF_QUANT         147        0          0
2005.SE_M.S01.T001.DF_QUANT         517        0          0
2005.SE_S.S01.T001.DF_QUANT         136        0          0
2005.DK_E.S01.T001.DF_PRICE         493        99        49
2005.DK_W.S01.T001.DF_PRICE         493        99        49
2005.FI_R.S01.T001.DF_PRICE         493        99        49
2005.NO_N.S01.T001.DF_PRICE         493        99        49
2005.NO_M.S01.T001.DF_PRICE         493        99        49
2005.NO_S.S01.T001.DF_PRICE         493        99        49
2005.NO_O.S01.T001.DF_PRICE         493        99        49
2005.SE_N.S01.T001.DF_PRICE         493        99        49
2005.SE_M.S01.T001.DF_PRICE         493        99        49
2005.SE_S.S01.T001.DF_PRICE         493        99        49
2010.DK_E.S01.T001.DF_QUANT         20.3       0.1         0
2010.DK_W.S01.T001.DF_QUANT         29.6       0.1         0
2010.FI_R.S01.T001.DF_QUANT         500         0.1         0
2010.NO_N.S01.T001.DF_QUANT         210         0.1         0
2010.NO_M.S01.T001.DF_QUANT         210         0.1         0
2010.NO_S.S01.T001.DF_QUANT         928         0.1         0
2010.NO_O.S01.T001.DF_QUANT         403         0.1         0
2010.SE_N.S01.T001.DF_QUANT         184         0.1         0
2010.SE_M.S01.T001.DF_QUANT         647         0.1         0
2010.SE_S.S01.T001.DF_QUANT         169         0.1         0
2010.DK_E.S01.T001.DF_PRICE         493        99        49
2010.DK_W.S01.T001.DF_PRICE         493        99        49
2010.FI_R.S01.T001.DF_PRICE         493        99        49
2010.NO_N.S01.T001.DF_PRICE         493        99        49
2010.NO_M.S01.T001.DF_PRICE         493        99        49
2010.NO_S.S01.T001.DF_PRICE         493        99        49
2010.NO_O.S01.T001.DF_PRICE         493        99        49
2010.SE_N.S01.T001.DF_PRICE         493        99        49
2010.SE_M.S01.T001.DF_PRICE         493        99        49
2010.SE_S.S01.T001.DF_PRICE         493        99        49
2015.DK_E.S01.T001.DF_QUANT         101.7       0.1         0
2015.DK_W.S01.T001.DF_QUANT         148.2       0.1         0
2015.FI_R.S01.T001.DF_QUANT        1375         0.1         0
2015.NO_N.S01.T001.DF_QUANT         337         0.1         0
2015.NO_M.S01.T001.DF_QUANT         337         0.1         0
2015.NO_S.S01.T001.DF_QUANT        1491         0.1         0
2015.NO_O.S01.T001.DF_QUANT         647         0.1         0
2015.SE_N.S01.T001.DF_QUANT         403         0.1         0
2015.SE_M.S01.T001.DF_QUANT        1414         0.1         0
2015.SE_S.S01.T001.DF_QUANT         371         0.1         0
2015.DK_E.S01.T001.DF_PRICE         493        99        49
2015.DK_W.S01.T001.DF_PRICE         493        99        49
2015.FI_R.S01.T001.DF_PRICE         493        99        49
2015.NO_N.S01.T001.DF_PRICE         493        99        49
2015.NO_M.S01.T001.DF_PRICE         493        99        49
2015.NO_S.S01.T001.DF_PRICE         493        99        49
2015.NO_O.S01.T001.DF_PRICE         493        99        49
2015.SE_N.S01.T001.DF_PRICE         493        99        49
2015.SE_M.S01.T001.DF_PRICE         493        99        49
2015.SE_S.S01.T001.DF_PRICE         493        99        49
2020.DK_E.S01.T001.DF_QUANT         187.2       0.1         0
2020.DK_W.S01.T001.DF_QUANT         272.8       0.1         0
2020.FI_R.S01.T001.DF_QUANT        2091         0.1         0
2020.NO_N.S01.T001.DF_QUANT         502         0.1         0
2020.NO_M.S01.T001.DF_QUANT         502         0.1         0
2020.NO_S.S01.T001.DF_QUANT        2216         0.1         0
2020.NO_O.S01.T001.DF_QUANT         962         0.1         0
2020.SE_N.S01.T001.DF_QUANT         641         0.1         0
2020.SE_M.S01.T001.DF_QUANT        2253         0.1         0
2020.SE_S.S01.T001.DF_QUANT         591         0.1         0
2020.DK_E.S01.T001.DF_PRICE         493        99        49
2020.DK_W.S01.T001.DF_PRICE         493        99        49
2020.FI_R.S01.T001.DF_PRICE         493        99        49
2020.NO_N.S01.T001.DF_PRICE         493        99        49
2020.NO_M.S01.T001.DF_PRICE         493        99        49
2020.NO_S.S01.T001.DF_PRICE         493        99        49
2020.NO_O.S01.T001.DF_PRICE         493        99        49
2020.SE_N.S01.T001.DF_PRICE         493        99        49
2020.SE_M.S01.T001.DF_PRICE         493        99        49
2020.SE_S.S01.T001.DF_PRICE         493        99        49
;

DEF_STEPS2(Y,IR,S,T,DF_QP,DEF)$((2000 LE YVALUE(Y)) AND (2004 GT YVALUE(Y)))=DEF_STEPS2('2005',IR,S,'T001',DF_QP,DEF);
DEF_STEPS2(Y,IR,S,T,DF_QP,DEF)$((2004 LE YVALUE(Y)) AND (2010 GT YVALUE(Y)))=DEF_STEPS2('2005',IR,S,'T001',DF_QP,DEF);
DEF_STEPS2(Y,IR,S,T,DF_QP,DEF)$((2010 LE YVALUE(Y)) AND (2015 GT YVALUE(Y)))=DEF_STEPS2('2010',IR,S,'T001',DF_QP,DEF);
DEF_STEPS2(Y,IR,S,T,DF_QP,DEF)$((2015 LE YVALUE(Y)) AND (2020 GT YVALUE(Y)))=DEF_STEPS2('2015',IR,S,'T001',DF_QP,DEF);
DEF_STEPS2(Y,IR,S,T,DF_QP,DEF)$(2020 LE YVALUE(Y))=DEF_STEPS2('2020',IR,S,'T001',DF_QP,DEF);

$label FSS_var2001_label1
