PARAMETER DEFP_BASE(RRR)  'Nominal annual average consumer electricity price (including taxes) in the base year (Money/MWh)'         
/                                                                                                                                    
DK1                                                                                                                          40      
DK2                                                                                                                          40      
FIN                                                                                                                          40      
DE4-E                                                                                                                        50.2    
DE4-N                                                                                                                        50.2    
DE4-S                                                                                                                        50.2    
DE4-W                                                                                                                        50.2    
NL                                                                                                                           50.2    
NO1                                                                                                                          40      
NO2                                                                                                                          40      
NO3                                                                                                                          40      
NO4                                                                                                                          40      
NO5                                                                                                                          40      
SE1                                                                                                                          40      
SE2                                                                                                                          40      
SE3                                                                                                                          40      
SE4                                                                                                                          40      
UK                                                                                                                           40      
EE                                                                                                                           40      
LV                                                                                                                           40      
LT                                                                                                                           40      
PL                                                                                                                           40      
/;                                                                                                                                   
