* PARAMETER DEFP_BASE gives an annual average consumer price
* of electricity (including taxes) in the base year.
* Unit: EUR90/MWh

* It is used as nominal value for calculations in relation to elastic demands.

PARAMETER DEFP_BASE(RRR)  'Nominal annual average consumer electricity price (Money/MWh)'
/*
/
DK_E                          105
DK_W                          105
EE_R                          28
FI_R                          40
DE_CS                         66
DE_NE                         66
DE_NW                         66
LV_R                          29
LT_R                          29
NO_N                          37
NO_M                          37
NO_S                          37
NO_O                          37
PL_R                          26
RU_W                          26
RU_K                          26
SE_N                          31
SE_M                          31
SE_S                          31
/;
*/


*

/
DK_E                          40
DK_W                          40
EE_R                          40
FI_R                          40
DE_CS                         40
DE_NE                         40
DE_NW                         40
LV_R                          40
LT_R                          40
NO_N                          40
NO_M                          40
NO_S                          40
NO_O                          40
PL_R                          40
RU_W                          40
RU_K                          40
SE_N                          40
SE_M                          40
SE_S                          40
/;

 DEFP_BASE(RRR)=33;