SET DHF_U3(DHF)  'Downwards steps in elastic heat demand, absolute Money and fraction of nominal demand data format'
/                                                                                                                   
* Empty, i.e. no elasticity in demand from DHF_U3                                                                   
/;                                                                                                                  
