SET DHF_D2(DHF)  'Downwards steps in elastic heat demand, absolute Money and MW-incremental data format'
/                                                                                                       
* Empty, i.e. no elasticity in demand from DHF_D2                                                       
/;                                                                                                      
