PARAMETER DISCOST_H(AAA)  'Cost of heat distribution (Money/MWh)'     
* Areas merged, average values used                                   
/                                                                     
DK1_Large                                                         2   
DK1_Rural                                                         2   
DK1_Medium                                                        2   
DK2_Large                                                         2   
DK2_Rural                                                         2   
DK2_Medium                                                        2   
DK2_MedSmall                                                      2   
DK1_Small                                                         2   
DK1_MedSmall                                                      2   
DK2_Small                                                         2   
DK2_NoDH                                                          2   
DK1_NoDH                                                          2   
DK2_Offshore                                                      2   
DK1_Offshore                                                      2   
FinA                                                              2   
DE4-E_A                                                           2   
DE4-E_Offshore_A                                                  2   
DE4-N_A                                                           2   
DE4-N_Offshore_A                                                  2   
DE4-S_A                                                           2   
DE4-W_A                                                           2   
DE4-W_Offshore_A                                                  2   
EE_Enefit                                                         2   
EE_Industry                                                       2   
EE_Kohtla_Jarve                                                   2   
EE_Narva                                                          2   
EE_Parnu                                                          2   
EE_Rural                                                          2   
EE_Sillamae                                                       2   
EE_Tallinn                                                        2   
EE_Tartu                                                          2   
EE_Urban                                                          2   
LT_KauU                                                           2   
LT_KlaU                                                           2   
LT_Other_DH                                                       2   
LT_Panevezys                                                      2   
LT_Rural                                                          2   
LT_SiaU                                                           2   
LT_VilU                                                           2   
LV_Other_DH                                                       2   
LV_RigaR                                                          2   
LV_Rural                                                          2   
NL_A                                                              2   
PL_A                                                              2   
PL_Rural                                                          2   
UK_A                                                              2   
UK_Offshore                                                       2   
SE1A                                                              2   
SE2A                                                              2   
SE3A                                                              2   
SE4A                                                              2   
                                                                      
                                                                      
                                                                      
                                                                      
                                                                      
                                                                      
                                                                      
                                                                      
                                                                      
                                                                      
/;                                                                    
