PARAMETER DISCOST_H(AAA)  'Cost of heat distribution (Money/MWh)'
/
DK_E_Urban                    1.00
DK_W_Urban                    1.00
EE_R_Urban                    1.00
FI_R_Urban                    1.00
FI_R_Rural                    2.00
DE_CS_A1                      2.00
DE_NE_A1                      2.00
DE_NW_A1                      2.00
LV_R_Urban                    1.00
LT_R_Urban                    1.00
PL_R_Urban                    2.31
RU_W_Urban                    1.00
RU_K_Urban                    1.00
SE_M_Urban                    1.00
DK_E_Rural                    2.00
DK_W_Rural                    2.00
EE_R_Rural                    2.00
LV_R_Rural                    2.00
LT_R_Rural                    2.00
NO_N_Rural                    2.00
NO_M_Rural                    2.00
NO_S_Rural                    2.00
NO_O_Rural                    2.00
PL_R_Rural                    2.31
RU_W_Rural                    2.00
RU_K_Rural                    2.00
SE_N_Rural                    2.00
SE_M_Rural                    2.00
SE_S_Rural                    2.00
SE_S_Bio                      2.00
SE_M_Bio                      2.00
SE_N_Bio                      2.00
/;