PARAMETER DISCOST_E(RRR)  'Cost of electricity distribution (Money/MWh)'
/
DK_E                          5.00
DK_W                          5.00
EE_R                          5.00
FI_R                          5.00
DE_CS                         5.00
DE_NE                         5.00
DE_NW                         5.00
LV_R                          5.00
LT_R                          8.86
NO_N                          5.00
NO_M                          5.00
NO_S                          5.00
NO_O                          5.00
PL_R                          5.00
RU_W                          5.00
RU_K                          5.00
SE_N                          5.00
SE_M                          5.00
SE_S                          5.00
/;