PARAMETER DISLOSS_E(RRR)  'Loss in electricity distribution'
/
DK_E                          0.050
DK_W                          0.050
EE_R                          0.100
FI_R                          0.050
DE_CS                         0.050
DE_NE                         0.050
DE_NW                         0.050
LV_R                          0.200
LT_R                          0.120
NO_N                          0.050
NO_M                          0.050
NO_S                          0.050
NO_O                          0.050
PL_R                          0.100
RU_W                          0.100
RU_K                          0.100
SE_N                          0.050
SE_M                          0.050
SE_S                          0.050
/;