SET FDATASET  'Characteristics of fuels '                
/                                                        
FDACRONYM 'Acronym (name) of the fuel'                   
FDNB      'Fuel number for internal use'                 
FDCO2     'Emission CO2 (kg/GJ)'                         
FDSO2     'Emission SO2 (kg/GJ)'                         
FDN2O     'Emission N2O (kg/GJ)'                         
FDRE         "Share of fuel considered renewable ([1;0])"
/;                                                       
