TABLE FGEMAX(CCCRRRAAA,FFF)   'Maximum electricity generation by fuel (MWh)'                                                             
*                                                                            NATGAS       MUNIWASTE     STRAW       WOOD        WOODWASTE
* DK_W                                                                       0                                                           
;                                                                                                                                        
