TABLE FKMAXNA(YYY,FFF)     'Minimum capacity by fuel per year (MW)'                                                             
*                                                                   NATGAS       MUNIWASTE     STRAW       WOOD        WOODWASTE
* 2012.DK_W                                                                                    0           0                    
;                                                                                                                               
