TABLE FMAXINVESTNA(YYY,FFF)        'Maximum investment by year and fuel type for each year simulated (MW)(aggregated countries)'                                                             
*                                                                                                                                NATGAS       MUNIWASTE     STRAW       WOOD        WOODWASTE
* 2012.DK_W                                                                                                                                                                                  
;                                                                                                                                                                                            
