* File for holding TABLE GDATA for the Balmorel model, version 3.01 (April 2009).


TABLE GDATA(GGG,GDATASET)  'Technologies characteristics'

                                   GDTYPE       GDFUEL      GDCV        GDCB       GDFE      GDCH4      GDNOX        GDDESO2   GDINVCOST0  GDOMFCOST0    GDOMVCOST0  GDFROMYEAR   GDLIFETIME   GDKVARIABL
BACKSTOP                           GCND         DUMMY       0           0          0.4                                                                   288
EH-E9                              GETOH        ELECTRIC    0           0          0.97      0          0            0         0.021       0             0.007       1970         20           1
EH-P9                              GETOH        ELECTRIC                           3                                           0.238       2.26          0.95
DE_Base                            GWND         WIND        0           0          1         0          0            0         0.75        7.5           0
DK_E_CHP1                          GBPR         NATGAS                  0.660      0.880                                       2.0660      82.620        0.0250
G-HSTORE                           GHSTO        HEAT        8           8          1                                           0.0021                                2010         20           1
DK_E_CHP2                          GBPR         NATGAS                  1.009      0.850                                       2.0659      82.619        0.0250
DK_E_CHP3                          GBPR         STRAW                   0.349      0.860                                       2.0660      82.619        0.0250
HO-B8-FO                           GHOB         FUELOIL                            0.85                                        0.06        0.9           0.75
DK_E_CHP4                          GBPR         MUNIWASTE               0.369      0.860                                       2.0660      82.620        0.0250
DK_E_CHP5                          GBPR         FUELOIL                 0.280      0.920                                       2.0660      82.620        0.0250
DK_Offshore_WI-S0                  GWND         WIND                               1                                           1.0111      13.683        0
GT-C8-LO                           GCND         LIGHTOIL                           0.30      1.50       250          0         0.40        16            1
DK_E_Rural_ST-B8-CO                GBPR         COAL                    1.059      0.850     1.499      400          0         0.9179      36.720        2.1600
DK_E_Rural_ST-B8-FO                GBPR         FUELOIL                 0.75       0.850     3          240          0         1.0330      41.310        2.4300
ST-C7-CO                           GCND         COAL                               0.331     1.5        400          0         1.275       51            2
ST-C7-FO                           GCND         FUELOIL                            0.331     3          240          0         1.148       45.9          1.8
ST-C8-COs                          GCND         COAL                               0.38      1.5        400          0.98      0.893       35.7          2.1
DK_E_Rural_ST-E7-CO                GEXT         COAL        0.2         4.760      0.331     1.499      400          0         1.275       51            2
DK_E_Rural_ST-E8-ORs               GEXT         COAL        0.15        4.760      0.418     1.499      200          0.98      0.9649      38.610        1.6380
DK_E_Rural_ST-E8-ST                GEXT         STRAW       0.2         0.7        0.342     32         128          0         1.6069      64.260        2.0599
DK_E_Rural_WI                      GWND         WIND                               1                                           0.7807      8.4412        0
DK_E_Urban_CC-B8-NG                GBPR         NATGAS                  0.349      0.879     2.500      100          0         0.5469      13.680        0.5339
DK_E_Urban_ST-B8-NG                GBPR         NATGAS                  0.283      0.850     2.5        65.          0         0.9179      36.720        2.1600
DK_E_Urban_ST-B9-ST                GBPR         STRAW                   0.430      0.880     32         128          0         2.0659      82.620        2.0250
DK_E_Urban_ST-E0-NGsn              GEXT         NATGAS      0.15        0.9        0.409     2.5        120          0.95      1.4770      59.069        1.0920
DK_E_Urban_ST-E0-Wosn              GEXT         WOOD        0.15        0.9        0.409     32         64           0.95      1.4770      59.069        1.0920
DK_E_Urban_ST-E7-CO                GEXT         COAL        0.20        0.560      0.331     1.499      400          0         1.2749      51            2
DK_E_Urban_ST-E9-Cosn              GEXT         COAL        0.15        0.610      0.418     1.5        200          0.98      0.965       38.61         1.638
DK_W_CHP1                          GBPR         NATGAS                  0.969      0.879                                       2.0659      82.620        0.0250
DK_W_CHP2                          GBPR         NATGAS                  1.490      0.855                                       2.0660      82.620        0.0250
DK_W_CHP3                          GBPR         MUNIWASTE               0.180      0.857                                       2.0659      82.620        0.0250
DK_W_CHP4                          GBPR         STRAW                   0.419      0.862                                       2.0660      82.620        0.0250
DK_W_CHP5                          GBPR         STRAW                   0.079      0.922                                       2.0659      82.620        0.0250
DK_W_CHP6                          GBPR         FUELOIL                 0.279      0.879                                       2.0660      82.620        0.0250
DK_W_Odense_ST-B9-MW               GBPR         MUNIWASTE               0.379      0.88      5.999      148          0         2.0659      82.620        2.0250
DK_W_Odense_ST-E7-NG               GEXT         NATGAS      0.20        0.519      0.379     2.499      240          0         1.0709      42.840        1.6479
DK_W_Odense_ST-E9-Cosn             GEXT         COAL        0.15        0.6        0.418     1.499      199          0.98      0.9649      38.610        1.6379
DK_W_Rural_CC-B8-NG                GBPR         NATGAS                  1.261      0.879     2.500      210          0         0.5470      13.680        0.5339
DK_W_Rural_ST-B8-CO                GBPR         COAL                    0.453      0.850     1.500      400          0.80      0.9179      36.720        2.1600
DK_W_Rural_ST-B8-NG                GBPR         NATGAS                  0.509      0.850     2.500      240          0         0.9179      36.720        2.1600
DK_W_Rural_ST-B9-MW                GBPR         MUNIWASTE               0.524      0.880     6.000      148          0         2.0660      82.620        2.0250
DK_W_Rural_ST-B9-ST                GBPR         STRAW                   0.824      0.879     32         128          0         2.0659      82.620        2.0250
DK_W_Rural_ST-B9-WO                GBPR         WOOD                    0.504      0.879     32         128          0         2.0659      82.620        2.0250
DK_W_Rural_WI                      GWND         WIND                               1                                           0.7153      6.8712        0
DK_W_Trefor_ST-E7-FO               GEXT         FUELOIL     0.2         0.5        0.330     3          240          0         1.2050      48.2          1.8539
DK_W_Trefor_ST-E9-NGn              GEXT         NATGAS      0.15        0.730      0.439     2.499      120          0         0.7350      29.419        1.2480
DK_W_Urban_ST-E9-Cosn              GEXT         COAL        0.15        1.678      0.418     1.499      200          0.98      0.9649      38.609        1.6379
DK_W_Aalborg_ST-E7-CO              GEXT         COAL        0.20        6.640      0.331     1.500      400          0         1.275       51            2
DK_W_Aalborg_ST-E9-Cosn            GEXT         COAL        0.15        0.740      0.47      1.500      200          0.98      0.9649      38.609        1.6379
DK_W_Aarhus_ST-B9-MW               GBPR         MUNIWASTE               1.200      0.88      5.999      148          0         2.0659      82.620        2.0250
DK_W_Aarhus_ST-E8-Cos              GEXT         COAL        0.20        0.644      0.379     1.5        400          0.97      0.9369      37.490        2.1630
DK_W_Aarhus_ST-E8-ST               GEXT         STRAW       0.18        0.589      0.430     32         128          0.98      1.6069      64.260        2.0599
FI_R_Decen_CC-E9-NGn               GEXT         NATGAS      0.14        0.875      0.5       2.499      70.          0         0.4799      12            0.6000
FI_R_Decen_ST-E9-NGn               GEXT         NATGAS      0.15        1.6        0.439     2.500      120          0         0.735       29.42         1.2480
CC-B9-NGn                          GBPR         NATGAS                  0.763      0.900     2.499      70.          0         0.5759      14.4          0.5630
ST-B8-CO                           GBPR         COAL                    0.5        0.85      1.5        400          0         0.918       36.72         2.16
ST-B8-FO                           GBPR         FUELOIL                 0.5        0.85      3          240          0         1.033       41.31         2.43
ST-B8-NG                           GBPR         NATGAS                  0.5        0.85      2.5        240          0         0.918       36.72         2.16
FI_R_Industry_ST-B8-PE             GBPR         PEAT                    0.5        0.850     3          240          0         1.0330      41.310        2.4300
ST-B8-WW                           GBPR         WOODWASTE               0.5        0.850     3          240          0         1.0330      41.310        2.4300
FI_R_Industry_ST-B9-PE             GBPR         PEAT                    0.289      0.880     1.5        400          0         1.1479      45.9          2.0250
FI_R_Industry_ST-B9-WO             GBPR         WOOD                    0.406      0.880     32         128          0         2.0659      82.620        2.0250
FI_R_Industry_ST-B9-WW             GBPR         WOODWASTE               0.483      0.880     32         128          0         2.0659      82.620        2.0250
FI_R_Rural_CC-E9-NGn               GEXT         NATGAS      0.14        0.419      0.393     2.499      70.          0         0.4799      12            0.6000
HO-B8-CO                           GHOB         COAL                               0.761                                       0.12        3.6           1.5
HO-B8-PE                           GHOB         PEAT                               0.761                                       0.12        3.6           1.5
FI_R_Rural_NU-C8-NU                GCND         NUCLEAR                            0.362     0          0            0         1.3490      26.984        0.9812
FI_R_Rural_ST-B8-PE                GBPR         PEAT                    0.5        0.850     3.000      240          0         1.0329      41.310        2.4300
FI_R_Rural_ST-B9-PE                GBPR         PEAT                    0.586      0.880     1.499      400          0         1.1479      45.900        2.0250
FI_R_Rural_ST-B9-WW                GBPR         WOODWASTE               0.383      0.88      32         128          0         2.0660      82.620        2.0250
FI_R_Rural_ST-C0-Fosn              GCND         FUELOIL                            0.455     2.999      24.          0.95      0.7170      28.679        0.9729
FI_R_Rural_ST-C8-CO                GCND         COAL                               0.379     1.5        400          0         0.85        34            2
FI_R_Rural_ST-C8-FO                GCND         FUELOIL                            0.380     3          240          0         0.7650      30.600        1.7999
FI_R_Rural_ST-C8-NG                GCND         NATGAS                             0.398     2.499      240          0         0.6800      27.200        1.5999
ST-C8-Pes                          GCND         PEAT                               0.38      1.5        400          0.95      0.893       35.7          2.1
ST-C8-WW                           GCND         WOODWASTE                          0.342     32         128          0         1.53        61.2          2
ST-C9-Cosn                         GCND         COAL                               0.418     1.5        200          0.95      0.919       36.77         1.591
ST-C9-Pen                          GCND         PEAT                               0.376     1.5        200          0         0.876       35.02         1.515
FI_R_Rural_ST-E0-Wosn              GEXT         WOODWASTE  0.15         1.35       0.410     32         50.          0.95      1.4770      59.069        1.0920
FI_R_Rural_ST-E7-CO                GEXT         COAL        0.2         0.536      0.330     1.500      400          0         1.2749      51            2
FI_R_Rural_ST-E7-NG                GEXT         NATGAS      0.2         0.569      0.379     2.500      240          0         1.0709      42.840        1.6480
ST-E8-PE                           GEXT         PEAT        0.2         0.764      0.342     1.5        400          0         0.893       35.7          2.06
FI_R_Rural_ST-E9-Cosn              GEXT         COAL        0.15        1.127      0.418     1.500      200          0.95      0.9649      38.609        1.6379
FI_R_Rural_ST-E9-WO                GEXT         WOODWASTE  0.15         0.460      0.417     2.499      120          0         0.7350      29.420        1.2480
WI-L9                              GWND         WIND                               1                                           0.6435      5.565         0
FI_R_Urban_ST-E7-CO                GEXT         COAL        0.2         1.139      0.331     1.500      400          0         1.275       51            2
ST-E8-Cos                          GEXT         COAL        0.2         0.442      0.38      1.5        400          0.95      0.937       37.49         2.163
FI_R_Urban_ST-E9-Cosn              GEXT         COAL        0.15        0.470      0.418     1.500      200          0.95      0.9649      38.609        1.6379
FI_R_Urban_ST-E9-NGn               GEXT         NATGAS      0.15        0.951      0.439     2.499      120          0         0.7350      29.419        1.2480
HY-ROR                             GHYRR        WATER                              1                                           1           20            0
HY-S01                             GHYRS        WATER                              1                                           1           20            0
HY-S02                             GHYRS        WATER                              1                                           1           20            1
HY-S03                             GHYRS        WATER                              1                                           1           20            2
HY-S04                             GHYRS        WATER                              1                                           1           20            3
HY-S05                             GHYRS        WATER                              1                                           1           20            4
HY-S06                             GHYRS        WATER                              1                                           1           19.999        5
HY-S07                             GHYRS        WATER                              1                                           1           19.999        6
HY-S08                             GHYRS        WATER                              1                                           1           19.999        7
HY-S09                             GHYRS        WATER                              1                                           1           19.999        8
HY-S10                             GHYRS        WATER                              1                                           1           19.999        9
NO_S_Rural_CC_E0_NG                GEXT         NATGAS      0.13        1.5        0.579     5.000      10.          0         0.3899      10.5          1.12
ST-B9-MW                           GBPR         MUNIWASTE               0.25       0.88      6          148          0         2.066       82.62         2.025
NO_S_Rural_ST-B9-WO                GBPR         WOOD                    0.5        0.879     32         128          0         2.0659      82.620        2.0250
SE_M_Rural_CC-E0-NG_Ens            GEXT         NATGAS      0.13        1.5        0.579     4.999      10.          0         0.3899      10.5          1.1200
SE_M_Rural_NU-C8-NU                GCND         NUCLEAR                            0.351     0          0            0         1.3707      27.415        0.9969
SE_M_Rural_ST-B9-MW                GBPR         MUNIWASTE               0.387      0.879     6          148          0         2.0660      82.620        2.0250
ST-B9-WW                           GBPR         WOODWASTE               0.504      0.855     8.644      218          0         1.2395      49.572        2.3510
ST-C7-Fosn                         GCND         FUELOIL                            0.331     3          120          0.95      1.241       49.64         1.909
SE_M_Rural_ST-E0-Wosn              GEXT         WOOD        0.15        0.643      0.400     32         64           0.95      1.4769      59.070        1.0919
SE_M_Urban_ST-B9-WO                GBPR         WOOD                    0.488      0.879     32         128          0         2.0660      82.620        2.0250
SE_M_Urban_ST-E7-FO                GEXT         FUELOIL     0.2         0.304      0.330     3.000      240          0         1.205       48.2          1.8540
SE_M_Urban_St-E9-Cosn              GEXT         COAL        0.15        0.427      0.404     1.5        200          0.95      0.9649      38.610        1.6380
SE_N_Rural_ST-B9-MW                GBPR         MUNIWASTE               0.260      0.88      6          148          0         2.0660      82.62         2.0250
SE_N_Rural_ST-E9-PE                GEXT         PEAT        0.15        0.022      0.168     2.499      120          0         0.7350      29.420        1.2480
SE_S_Rural_CC-E0-NGn               GEXT         NATGAS      0.13        1.266      0.555     4.381      25.          0         0.4111      10.852        0.9977
HO-B8-MW                           GHOB         MUNIWASTE                          0.761                                       0.24        14.4          3
HO-B8-NG                           GHOB         NATGAS                             0.85                                        0.04        0.4           0.5
HO-B8-WO                           GHOB         WOOD                               0.761                                       0.24        14.4          3
SE_S_Rural_NU-C8-NU                GCND         NUCLEAR                            0.349     0          0            0         1.375       27.5          1
SE_S_Rural_ST-B9-ST                GBPR         STRAW                   0.575      0.880     32         128          0         2.0659      82.620        2.0250
SE_S_Rural_ST-E7-NG                GEXT         NATGAS      0.2         0.283      0.376     2.499      240          0         1.0709      42.840        1.6480
SE_S_Rural_ST-E9-WO                GEXT         WOOD        0.15        0.437      0.223     2.499      120          0         0.7350      29.420        1.2480
SE_S_Rural_WI-L0                   GWND         WIND                               1                                           0.6079      4.9200        0
DE_HO-CO                           GHOB         COAL        0           0          0.9       1.5        120          0         0.12        3.6           1.5
DE_HO-NG                           GHOB         NATGAS      0           0          0.9       2.5        150          0         0.04        0.4           0.5
DE_HO-FO                           GHOB         FUELOIL     0           0          0.91      3          120          0         0.06        0.9           0.75
DE_HO-MW                           GHOB         MUNIWASTE   0           0          0.89      6          120          0         0.24        14.4          3
DE-COND-COAL-0-00                  GCND         COAL        0           0          0.37      1.5        400          0.95      0.893       35.7          2.1
DE-COND-COAL-0-91                  GCND         COAL        0           0          0.42      1.5        200          0.95      0.893       35.7          2.1
DE-COND-GAS-0-00                   GCND         NATGAS      0           0          0.37      2.5        75           0         0.38        15.2          1.648
DE-COND-GAS-101-00                 GCND         NATGAS      0           0          0.38      2.5        75           0         0.38        15.2          1.648
DE-COND-LIGN-0-83                  GCND         LIGNITE     0           0          0.37      1.5        200          0.95      0.893       35.7          2.1
DE-COND-MISC-0-00                  GCND         MUNIWASTE   0           0          0.35      6          148          0         2.066       82.62         2
DE-COND-MISC-0-91                  GCND         MUNIWASTE   0           0          0.4       6          148          0         2.066       82.62         2
DE-COND-NUCL-0-00                  GCND         NUCLEAR     0           0          0.35      0          0            0         1.375       27.5          1
DE-COND-OIL-51-00                  GCND         FUELOIL     0           0          0.36      1.5        150          0         0.38        15.2          1.8
DE-EL-ST                           GESTO        ELECTRIC    8           8          0.8       0          0            0         0.5         5             0
DE-KWK-COAL-ST-00                  GEXT         COAL        0.19        0.39       0.33      1.5        400          0.95      0.893       35.7          2.1
DE-KWK-GAS-CC-91                   GEXT         NATGAS      0.19        0.86       0.56      2.5        70           0         0.38        9.5           0.475
DE-KWK-GAS-GT-00                   GEXT         NATGAS      0.19        0.52       0.33      2.5        240          0         0.38        15.2          0.95
DE-KWK-GAS-IC-00                   GEXT         NATGAS      0.19        0.57       0.38      2.5        240          0         0.38        15.2          0.95
DE-KWK-GAS-ST-00                   GEXT         NATGAS      0.19        0.39       0.34      2.5        240          0         0.714       28.56         1.648
DE-KWK-MISC-IC-00                  GEXT         MUNIWASTE   0.19        0.57       0.38      6          148          0         2.066       82.62         0.95
DE-KWK-MISC-ST-00                  GEXT         MUNIWASTE   0.19        0.39       0.36      6          148          0         2.066       82.62         0.95
DE-KWK-OIL-ST-00                   GEXT         FUELOIL     0.19        0.39       0.32      2.5        240          0         1.148       45.9          1.8
DE-COND-GAS-CC-0-91                GCND         NATGAS      0           0          0.58      2.5        70           0         0.38        9.5           0.475
DE-COND-COAL-0-83                  GCND         COAL        0           0          0.4       1.5        200          0.95      0.893       35.7          2.1
DE-COND-LIGN-0-00                  GCND         LIGNITE     0           0          0.35      1.5        400          0         0.893       35.7          2.1
DE-KWK-GAS-CC-00                   GEXT         NATGAS      0.19        0.86       0.55      2.5        70           0         0.38        9.5           0.475
DE-KWK-LIGN-ST-00                  GEXT         LIGNITE     0.19        0.39       0.3       1.5        400          0.95      0.893       35.7          2.1
DE-KWK-OIL-GT-00                   GEXT         FUELOIL     0.19        0.52       0.32      2.5        240          0         0.4         16            1


*Existing units - Lithuania
*
*
*
*
*
*
*
*
*
*
*
/*
ST-Con-L3-G                        GCND         NATGAS      0           0          0.38                 160          0         0           8.636         1.633       1995         20           0
ST-Con-L3-O                        GCND         FUELOIL     0           0          0.38                 160          0         0           0             1.633       1995         20           0
ST-Con-L3-V                        GCND         ORIMULSION  0           0          0.38                 160          0         0           0             1.633       1995         20           0
ST-Ext-K1-G                        GEXT         NATGAS      0.076       0.304      0.250                105          0         0           21.480        3.687       1995         20           0
ST-Ext-K1-O                        GEXT         FUELOIL     0.076       0.304      0.250                105          0         0           0             3.687       1995         20           0
ST-Ext-K2-G                        GEXT         NATGAS      0.093       0.463      0.310                105          0         0           21.480        3.687       1995         20           0
ST-Ext-K2-O                        GEXT         FUELOIL     0.093       0.463      0.310                105          0         0           0             3.687       1995         20           0
ST-Ext-L1-G                        GEXT         NATGAS      0.054       0.817      0.33                 160          0         0           8.6360        1.801       1995         20           0
ST-Ext-L1-O                        GEXT         FUELOIL     0.054       0.817      0.33                 160          0         0           0             1.801       1995         20           0
ST-Ext-M-O                         GEXT         FUELOIL     0.086       0.345      0.27                 145          0         0           39.730        2.484       1995         20           0
ST-Ext-V3-G                        GEXT         NATGAS      0.120       0.568      0.357                125          0         0           20.408        0.255       1995         20           0
ST-Ext-V3-O                        GEXT         FUELOIL     0.120       0.568      0.357                125          0         0           0             0.255       1995         20           0
WIND-L-LT                          GWND         WIND        0           0          1                    0            0         1.5         4.06          0           2004         20           0
Kruonis                            GESTO        ELECTRIC    11.75       11.75      0.72                 0            0         2           0.14          1.058       1995         20           0

*Existing units - Latvia
DH-Old-B-LV                        GHOB         WOOD        0           0          0.62                 110          0         0           16.1          0.98        1980         25           0
DH-Old-G-LV                        GHOB         NATGAS      0           0          0.88                 105          0         0           7.05          0.45        1980         25           0
DH-Old-O-LV                        GHOB         FUELOIL     0           0          0.82                 130          0         0           9.0           0.79        1980         25           0
DH-Old-P-LV                        GHOB         PEAT        0           0          0.64                 105          0         0           16.5          0.84        1980         25           0
Hydro-LV                           GHYRR        WATER       0           0          1                    0            0         0           10.16         0.16        1939         50           0
ST-BP-1-OG                         GBPR         NATGAS      0           0.34       0.77                 105          0         0           30.5          1.61        1955         50           0
ST-Ext-22-OG                       GEXT         NATGAS      0.098       0.49       0.31                 105          0         0           15.8          0.83        1977         40           0
DH-OLD-RT-OG                       GHOB         NATGAS      0           0          0.9                  105          0         0           3.5           0.43        1966         25           0
SM-HPP-LV                          GHYRR        WATER       0           0          1                    0            0         0           25.4          0.45        1993         30           0
ST-BP-LV-OG                        GBPR         NATGAS      0           0.23       0.78                 105          0         0           48.7          3.6         1930         30           0
GE-BP-LV-G                         GBPR         NATGAS      0           0.86       0.84                 70           0         0           23.1          1.9         1997         25           0
BIO-GAS-LV                         GCND         WOOD        0           0          0.38                 70           0         0           26.1          2.2         2002         25           0

*Existing units - Estonia
DH-Old-B-EE                        GHOB         WOOD        0           0          0.671                110          0         0           13.7445       1.0437      1970         20           0
DH-Old-G-EE                        GHOB         NATGAS      0           0          0.85                 105          0         0           9.35          0.71        1970         20           0
DH-Old-O-EE                        GHOB         FUELOIL     0           0          0.85                 130          0         0           9.8175        0.7455      1970         20           0
DH-Old-P-EE                        GHOB         PEAT        0           0          0.671                105          0         0           13.7445       1.0437      1970         20           0
DH-Old-S-EE                        GHOB         SHALE       0           0          0.335                105          0         0           9.8175        0.7455      1970         20           0
DH-Old-O-IRU                       GHOB         FUELOIL     0           0          0.92                 130          0         0           9.8175        0.7455      1970         20           0
ST-Con-4-S                         GCND         SHALE       0           0          0.306                150          0.72      0           14.835        1.388       1970         20           0
ST-Cond-4-S                        GCND         SHALE       0           0          0.290                150          0.72      0           18.77         1.388       1970         20           0
ST-Ext-41-OG                       GEXT         NATGAS      0.083       0.615      0.32                 115          0         0           21.480        3.687       1970         20           0
ST-BP-42-OG                        GBPR         NATGAS      0           0.461      0.83                 115          0         0           21.480        1.4         1970         20           0
ST-Con04-S                         GCND         SHALE       0           0          0.36                  40          0.975     0.54        16.00         1.103       2004         20           0
ST-Ext04-S                         GEXT         SHALE       0.15        0.85       0.36                  40          0.975     0.54        16.00         1.103       2004         20           0

*Refurbishments/new individual technologies - Lithuania
ST-Cond-LM-F1-G                    GCND         NATGAS      0           0          0.42                 160          0.95      0.212       7.09          1.633       2006         20           1
ST-Cond-LM-F1-O                    GCND         FUELOIL     0           0          0.42                 160          0.95      0           0             1.633       2006         20           1
ST-Cond-LM-F1-V                    GCND         ORIMULSION  0           0          0.42                 160          0.95      0           0             1.633       2006         20           1
ST-Ext-K1M-F4-G                    GEXT         NATGAS      0.076       0.304      0.25                 105          0         0.334       21.48         3.687       2006         20           1
ST-Ext-K1M-F4-O                    GEXT         FUELOIL     0.076       0.304      0.25                 105          0         0           0             3.687       2006         20           1
ST-Ext-K2M-F5-G                    GEXT         NATGAS      0.093       0.463      0.31                 105          0         0.207       21.48         3.687       2007         20           1
ST-Ext-K2M-F5-O                    GEXT         FUELOIL     0.093       0.463      0.31                 105          0         0           0             3.687       2007         20           1
ST-Ext-V31M-F2-G                   GEXT         NATGAS      0.120       0.568      0.357                125          0         0.112       20.408        0.255       2006         20           1
ST-Ext-V31M-F2-O                   GEXT         FUELOIL     0.120       0.568      0.357                125          0         0           0             0.255       2006         20           1
ST-Ext-V32M-F3-G                   GEXT         NATGAS      0.120       0.568      0.357                125          0         0.112       20.408        0.255       2011         20           1
ST-Ext-V32M-F3-O                   GEXT         FUELOIL     0.120       0.568      0.357                125          0         0           0             0.255       2011         20           1
NU-Con-In                          GCND         NUCLEAR     0           0          0.30                 0            0         0.04        40.442        1.048       2013         20           0

*Refurbishments/new individual technologies - Latvia
ST-BP-1M-G                         GBPR         NATGAS      0           0.99       0.87                 70           0         0           18.6          1.39        2006         30           0
NEW-HYDRO-LV                       GHYRR        WATER       0           0          1                    0            0         1.560       7.40          1.01        2010         50           1
ST-BP-PULP-LV                      GBPR         WOOD        0           0.37       0.7                  110          0         1.050       34.8          3.24        2007         30           1
ST-BP-IM-G                         GBPR         NATGAS      0           1.08       0.85                 70           0         0           22.0          1.53        2006         30           0
ST-B1-Bio-LV                       GBPR         WOOD        0           0.5        0.9                  64           0         1.702       20.0          1.13        2010         25           0
ST-B1-waste-LV                     GBPR         MUNIWASTE   0           0.5        0.9                  64           0         1.702       20.0          1.364       2010         25           0
CC-Ext-2M-G                        GEXT         NATGAS      0.191       1.29       0.550                70           0         0.358       11.6          0.68        2004         30           1

*New technologies - HOB
DH-New-B                           GHOB         WOOD        0           0          0.761                110          0         0.1         3.6           1.5         2002         20           1
DH-New-C                           GHOB         COAL        0           0          0.761                110          0         0.12        3.6           1.5         2002         20           1
DH-New-G                           GHOB         NATGAS      0           0          0.85                 105          0         0.03        0.4           0.5         2002         20           1
DH-New-O                           GHOB         FUELOIL     0           0          0.85                 130          0         0.05        0.42          0.525       2002         20           1
DH-New-P                           GHOB         PEAT        0           0          0.761                105          0         0.1         3.6           1.5         2002         20           1
DH-New-S                           GHOB         SHALE       0           0          0.335                105          0         0.05        0.42          0.525       2002         20           1
DH-New-W                           GHOB         MUNIWASTE   0           0          0.761                105          0         0.24        14.4          3           2004         20           1

*New common technologies - Condensing
CC-Con350-G                        GCND         NATGAS      0           0          0.56                 50           0         0.56        11.2          1.2         2004         30           1
GT-Con50-G                         GCND         NATGAS      0           0          0.34                 50           0         0.468       6.4           2.0         2004         25           1
NU-Con                             GCND         NUCLEAR     0           0          0.372                0            0         1.50        28.55         1.04        2004         30           1
NU-Con-GF                          GCND         NUCLEAR     0           0          0.30                 0            0         1.90        40.442        1.048       2004         30           1
ST-Con-C                           GCND         COAL        0           0          0.485                40           0.95      0.88        16.00         1.60        2004         30           1
ST-Con-G                           GCND         NATGAS      0           0          0.490                60           0         0.64        24.80         0.54        2004         30           1
ST-Con-O                           GCND         FUELOIL     0           0          0.485                40           0.95      0.88        16.00         1.60        2004         30           1
ST-Con-P                           GCND         PEAT        0           0          0.445                40           0.95      0.88        16.00         1.60        2004         30           1
FB-Con-P                           GCND         PEAT        0           0          0.370                40           0.95      0.65        19.50         1.44        2004         30           1

*New common technologies - Back Pressure
CC-BP-G                            GBPR         NATGAS      0           1.07       0.89                 50           0         0.56        8.00          2.80        2004         30           1
ST-BP-G                            GBPR         NATGAS      0           0.9        0.9                  40           0         0.64        24.8          1.13        2004         30           1
Eng-BP-G                           GBPR         NATGAS      0           0.9        0.88                 170          0         0.80        3.20          4.80        2004         20           1

*New common technologies - Extraction
CC-Ext-G                           GEXT         NATGAS      0.13        1.32       0.56                 50           0         0.56        11.20         1.20        2004         30           1
IGCC-Ext-C                         GEXT         COAL        0.15        0.85       0.43                 70           0         1.052       17.92         5.12        2004         25           1
ST-Ext-C                           GEXT         COAL        0.12        0.89       0.485                40           0.95      0.880       16.00         1.600       2004         30           1
ST-Ext-G                           GEXT         NATGAS      0.15        0.85       0.490                40           0         0.640       24.80         0.540       2004         20           1
ST-Ext-O                           GEXT         FUELOIL     0.12        0.89       0.485                40           0.95      0.880       16.00         1.600       2004         30           1
ST-Ext-P                           GEXT         PEAT        0.12        0.89       0.445                40           0.95      0.880       16.00         1.600       2004         30           1

*New common technologies - Other
WIND-L                             GWND         WIND        0           0          1                    0            0         0.64        6.4           5.68        1995         20           1
WIND-S                             GWND         WIND        0           0          1                    0            0         1.20        6.4           6.40        1995         20           0
*/

* NEW TECHNOLOGIES FROM NORDIC DATA SET

* Teknologier opdateret med teknologikataloget (undtagen smaa biomasse dampanlaeg)
WI-L15                             GWND         WIND        0           0          1         0          0            0         0.630       10.80       1.440         2015         20           1
WI-L20                             GWND         WIND        0           0          1         0          0            0         0.585       10.41       1.350         2020         20           1
WI-L25                             GWND         WIND        0           0          1         0          0            0         0.540       9.82        1.260         2025         20           1
WI-S15                             GWND         WIND        0           0          1         0          0            0         1.080       27.37       2.339         2015         20           1
WI-S20                             GWND         WIND        0           0          1         0          0            0         1.008       27.37       2.339         2020         20           1
WI-S25                             GWND         WIND        0           0          1         0          0            0         0.936       27.37       2.339         2025         20           1


* (Atomkraft baseret paat  paa det finske anlaeg:)
NU-C0-NU                           GCND         NUCLEAR     0           0          0.385     0          0            0         1.758       33.5        0.95          2000         20           1
NU-C2-NU                           GCND         NUCLEAR     0           0          0.42      0          0            0         1.671       30          0.9           2020         20           1

ST-C0-COsn                         GCND         COAL        0           0          0.485     1.5        40           0.95      0.752       21.88       1.231         2000         20           1
ST-C0-FOsn                         GCND         FUELOIL     0           0          0.485     3          24           0.95      0.677       19.7        1.108         2000         20           1
ST-C0-WOsn                         GCND         WOOD        0           0          0.45      32         64           0.95      0.936       35.98       1.943         2000         20           1

ST-E0-COsn                         GEXT         COAL        0.15        0.78       0.485     1.5        40           0.95      0.792       23.04       1.296         2000         20           1
ST-E0-FOsn                         GEXT         FUELOIL     0.15        0.78       0.485     3          24           0.95      0.713       20.74       1.166         2000         20           1
ST-E0-WOsn                         GEXT         WOOD        0.15        0.7        0.45      32         64           0.95      0.936       35.98       1.943         2000         20           1
ST-E0-NGsn                         GEXT         NATGAS      0.15        0.78       0.485     2.5        120          0.95      0.713       20.74       1.166         2000         20           1

ST-C1-COsn                         GCND         COAL        0           0          0.525     1.5        40           0.95      0.821       21.88       1.231         2010         20           1

ST-E1-COsn                         GEXT         COAL        0.15        0.95       0.525     1.5        40           0.95      0.864       23.04       1.296         2010         20           1
ST-E1-FOsn                         GEXT         FUELOIL     0.15        0.95       0.525     3          24           0.95      0.777       20.74       1.166         2010         20           1
ST-E1-WOsn                         GEXT         WOOD        0.15        0.76       0.465     32         64           0.95      0.936       35.98       1.943         2010         20           1

* Smaa modtryksanlaeg enegd endnu ikke opdateret
ST-B1-NGn                          GBPR         NATGAS      0           1          0.9       2.5        120          0         1.009       40.34       1.454         2010         20           1
ST-B1-FOn                          GBPR         FUELOIL     0           1          0.9       3          120          0         0.851       34.04       1.227         2010         20           1
ST-B1-STn                          GBPR         STRAW       0           0.5        0.9       32         64           0         1.702       68.08       1.364         2010         20           1
ST-B1-WOn                          GBPR         WOOD        0           0.5        0.9       32         64           0         1.702       68.08       1.364         2010         20           1

CC-C0-NGn                          GCND         NATGAS      0           0          0.58      2.5        70           0         0.359       9.57        1.026         2000         3            1
CC-E0-NGn                          GEXT         NATGAS      0.14        1.17       0.58      2.5        70           0         0.378       10.01       1.080         2000         20           1
CC-B0-NGn                          GBPR         NATGAS      0           0.9        0.92      2.5        70           0         0.504       7.20        1.979         2000         20           1
CC-C1-NGn                          GCND         NATGAS      0           0          0.60      2.5        70           0         0.376       8.55        1.026         2010         20           1
CC-E1-NGn                          GEXT         NATGAS      0.14        1.6        0.60      2.5        70           0         0.396       9.0         1.080         2010         20           1
CC-B1-NGn                          GBPR         NATGAS      0           1.1        0.935     2.5        70           0         0.504       7.2         1.979         2010         20           1

GT-C0-LO                           GCND         LIGHTOIL    0           0          0.33      1.5        200          0         0.263       5.3         0.8           2000         20           1
GT-C0-NG                           GCND         NATGAS      0           0          0.33      2.5        100          0         0.263       5.3         0.8           2000         20           1
GT-C2-LO                           GCND         LIGHTOIL    0           0          0.36      1.5        150          0         0.253       5.3         0.8           2020         20           1
GT-C2-NG                           GCND         NATGAS      0           0          0.36      2.5        75           0         0.253       5.3         0.8           2020         20           1

*WI-L0                             GWND         WIND         0           0          1         0          0            0         0.594       0           6.478         2000         20           1
*WI-L1                             GWND         WIND         0           0          1         0          0            0         0.497       0           5.758         2010         20           1
*WI-S0                             GWND         WIND         0           0          1         0          0            0         1.152       0           9.357         2000         20           1
*WI-S1                             GWND         WIND         0           0          1         0          0            0         0.828       0           7.198         2010         20           1

HO-B0-NG                           GHOB         NATGAS      0           0          0.95      2.5        120          0         0.04        0.4         0.5           2000         20           1
HO-B0-FO                           GHOB         FUELOIL     0           0          0.95      3          120          0         0.06        0.9         0.75          2000         20           1
HO-B0-ST                           GHOB         STRAW       0           0          0.85      32         120          0         0.24        14.4        3             2000         20           1
HO-B0-WO                           GHOB         WOOD        0           0          0.85      32         120          0         0.24        14.4        3             2000         20           1

* Varmepumper endnu ikke i kke opdateret
EH-P1                              GETOH        ELECTRIC    0           0          3.5       0          0            0         0.55        0.85        1.81          2010         20           1
EH-P0                              GETOH        ELECTRIC    0           0          3.25      0          0            0         0.6         0.9         2.03          2000         20           1


* Teknologier ikke opdatopedateret med teknologikataloget

NU-E0-NU                           GEXT         NUCLEAR     0.15        0.5        0.385     0          0            0         1.339       26.78       0.974         2000         20           1
NU-E2-NU                           GEXT         NUCLEAR     0.15        0.5        0.42      0          0            0         1.268       25.37       0.923         2020         20           1
ST-E0-PEsn                         GEXT         PEAT        0.15        0.7        0.45      1.5        40           0.95      0.836       33.46       1.114         2000         20           1
ST-E0-WWsn                         GEXT         WOODWASTE  0.15         0.7        0.41      32         64           0.95      1.477       59.07       1.092         2000         20           1
ST-B1-WWn                          GBPR         WOODWASTE  0            0.5        0.9       32         64           0         1.702       68.08       1.364         2010         20           0
ST-E1-PEsn                         GEXT         PEAT        0.15        0.7        0.41      1.5        40           0.95      0.787       31.49       1.114         2010         20           1
ST-B1-PEn                          GBPR         PEAT        0           0.5        0.9       1.5        200          0         0.946       37.82       1.364         2010         20           1
CC-C1-COn                          GCND         COAL        0           0          0.475     1.5        70           0         1.02        25.5        1             2010         20           1
CC-E1-COn                          GEXT         COAL        0.15        0.772      0.475     1.5        70           0         1.224       30.6        1.2           2010         20           1
CC-C1-WOn                          GCND         WOOD        0           0          0.475     32         70           0         1.08        27          1             2010         20           1
CC-E1-WOn                          GEXT         WOOD        0.15        0.772      0.475     32         70           0         1.224       30.6        1.2           2010         20           1
HO-B0-PE                           GHOB         PEAT        0           0          0.85      1.5        120          0         0.12        3.6         1.5           2000         20           1

*WI-L0                             GWND         WIND         0           0          1         0          0            0         0.608      4.92        0             2000         20           1
*WI-S1                             GWND         WIND         0           0          1.5       0          0            0         0.96       0           6.8           2010         20           1
*EH-P1                             GETOH        ELECTRIC     0           0          3.5       0          0            0         0.213      1.81        0.85          2010         20           0

/*
* New technologies in Estonia 
ST-Ext-Tartu                       GEXT         WOOD        0.16        0.5        0.3842    0          40           0         0.634       11.52         1.152       2009         30           1
ST-Ext-Parnu                       GEXT         WOOD        0.16        0.5        0.3842    0          40           0         0.634       11.52         1.152       2009         30           1
ST-Ext-Ahtme                       GEXT         WOOD        0.16        0.5        0.3842    0          40           0         0.634       11.52         1.152       2009         30           1
ST-Ext-Vao                         GEXT         WOOD        0.16        0.5        0.3842    0          40           0         0.634       11.52         1.152       2009         30           1

* ...on 220908 by Leo
ST-Ext-Iru-W                       GBPR         MUNIWASTE   0           0.5        0.9       0          64           0         1.702       20.0          1.364       2010         25           1
ST-Ext-Bio                         GEXT         WOOD        0.16        0.5        0.3842    0          40           0         0.634       11.52         1.152       2009         30           1


* New/redefined technologies in Estonia  
ST-Con-4M-F7                       GCND         SHALE        0           0         0.29      0          90           0.99       0.064      48.00          0          2010         10           1
ST-Con-S                           GCND         SHALE        0           0         0.388     0          40           0.99       1.07       33.00          0          2012         30           1
ST-Con-S-SC                        GCND         SHALE        0           0         0.415     0          40           0.99       1.18       33.00          0          2012         30           1
*/

/*
* POLAND
El-hc-SO2-O500                     GCND         COAL2       0           0          0.369     0          208          0.229     1           41.550        0.929       1980         20           0
El-hc-SO2-O500_08                  GCND         COAL2       0           0          0.369     0          197          0.385     1           41.550        0.929       1980         20           0
El-hc-SO2-U500                     GCND         COAL        0           0          0.334     0          185          0.065     1           39.668        0.844       1980         20           0
El-hc-SO2-U500_08                  GCND         COAL        0           0          0.334     0          176          0.221     1           39.668        0.844       1980         20           0
El-bc-SO2                          GCND         LIGNITE     0           0          0.342     0          131          0.094     1           44.907        1.196       1980         20           0
El-bc-SO2_14                       GCND         LIGNITE     0           0          0.342     0          127          0.444     1           44.907        1.196       1980         20           0
CHP-hc-SO2-O200                    GEXT         COAL        0.05        0.39       0.257     0          153          0.067     1           35.713        1.856       1980         20           0
CHP-hc-SO2-O200_08                 GEXT         COAL        0.05        0.39       0.257     0          153          0.208     1           35.713        1.856       1980         20           0
CHP-hc-SO2-O200_23                 GEXT         COAL        0.05        0.39       0.257     0          138          0.266     1           35.713        1.856       1980         20           0
CHP-hc-SO2-150-200                 GEXT         COAL        0.05        0.38       0.248     0          178          0.159     1           34.177        2.024       1980         20           0
CHP-hc-SO2-150-200_08              GEXT         COAL        0.05        0.38       0.248     0          166          0.234     1           34.177        2.024       1980         20           0
CHP-hc-SO2-150-200_14              GEXT         COAL        0.05        0.38       0.248     0          164          0.273     1           34.177        2.024       1980         20           0
CHP-hc-SO2-100-150                 GEXT         COAL        0.05        0.38       0.224     0          195          0.134     1           34.891        1.756       1980         20           0
CHP-hc-SO2-100-150_08              GEXT         COAL        0.05        0.38       0.224     0          184          0.244     1           34.891        1.756       1980         20           0
CHP-hc-SO2-100-150_14              GEXT         COAL        0.05        0.38       0.224     0          178          0.264     1           34.891        1.756       1980         20           0
CHP-hc-SO2-U100                    GEXT         COAL        0.05        0.41       0.281     0          199          0.294     1           43.702        1.684       1980         20           0
El-hc-Nox-O500                     GCND         COAL        0           0          0.362     0          185          0.643     1           54.868        0.860       1980         20           0
El-hc-Nox-O500_08                  GCND         COAL        0           0          0.362     0          169          0.857     1           54.868        0.860       1980         20           0
El-hc-Nox-U500                     GCND         COAL        0           0          0.338     0          180          0.815     1           51.509        1.270       1980         20           0
El-bc-NOx                          GCND         LIGNITE     0           0          0.313     0          156          0.853     1           38.073        0.856       1980         20           0
CHP-hc-Nox-O200                    GEXT         COAL        0.05        0.67       0.347     0          165          0.093     1           33.720        1.862       1980         20           0
CHP-hc-Nox-O200_08                 GEXT         COAL        0.05        0.67       0.347     0          165          0.575     1           33.720        1.862       1980         20           0
CHP-hc-Nox-O200_11                 GEXT         COAL        0.05        0.67       0.347     0          165          0.662     1           33.720        1.862       1980         20           0
CHP-hc-Nox-150-200                 GEXT         COAL        0.05        0.37       0.239     0          192          0.221     1           38.660        1.900       1980         20           0
CHP-hc-Nox-U150                    GEXT         COAL        0.05        0.44       0.284     0          219          0.113     1           43.242        1.682       1980         20           0
CHP-hc-Nox-U150_23                 GEXT         COAL        0.05        0.44       0.284     0          210          0.188     1           43.242        1.682       1980         20           0
El-hc-nat                          GCND         COAL        0           0          0.321     0          188          0.289     1           39.696        0.689       1980         20           0
El-hc-nat_08                       GCND         COAL        0           0          0.321     0          188          0.366     1           39.696        0.689       1980         20           0
El-hc-nat_11                       GCND         COAL        0           0          0.321     0          184          0.427     1           39.696        0.689       1980         20           0
El-bc-nat                          GCND         LIGNITE     0           0          0.326     0          153          0.298     1           40.977        1.142       1980         20           0
El-bc-nat_08                       GCND         LIGNITE     0           0          0.326     0          138          0.402     1           40.977        1.142       1980         20           0
CHP-hc-nat-O100                    GEXT         COAL2       0.05        0.81       0.352     0          164          0.185     1           41.417        1.991       1980         20           0
CHP-hc-nat-O100_08                 GEXT         COAL2       0.05        0.81       0.352     0          156          0.267     1           41.417        1.991       1980         20           0
CHP-hc-nat-U100                    GEXT         COAL        0.05        0.78       0.349     0          177          0.009     1           36.992        2.018       1980         20           0
El-hc-wap                          GCND         COAL        0           0          0.357     0          224          0.455     1           45.139        0.434       1980         20           0
El-hc-wap_08                       GCND         COAL        0           0          0.357     0          175          0.927     1           45.139        0.434       1980         20           0
El-bc-wap                          GCND         LIGNITE     0           0          0.351     0          137          0.684     1           39.609        1.301       1980         20           0
El-bc-wap_08                       GCND         LIGNITE     0           0          0.351     0          133          0.917     1           39.609        1.301       1980         20           0
CHP-hc-wap-O200                    GEXT         COAL        0.05        0.39       0.247     0          244          0.720     1           48.081        1.809       1980         20           0
CHP-hc-wap-100-200                 GEXT         COAL        0.05        0.39       0.252     0          211          0.231     1           36.089        1.958       1980         20           0
CHP-hc-wap-100-200_08              GEXT         COAL        0.05        0.39       0.252     0          188          0.357     1           36.089        1.958       1980         20           0
CHP-hc-wap-U100                    GEXT         COAL        0.05        0.59       0.303     0          251          0.109     1           30.947        2.013       1980         20           0
CHP-hc-wap-U100_08                 GEXT         COAL        0.05        0.59       0.303     0          202          0.266     1           30.947        2.013       1980         20           0
CHP-bc-wap                         GEXT         COAL2       0.05        1.86       0.417     0          158          0.000     1           43.347        3.430       1980         20           0
CHP-bc-wap_08                      GEXT         COAL2       0.05        1.86       0.417     0          158          0.688     1           43.347        3.430       1980         20           0
El-hc-n                            GCND         LIGNITE     0           0          0.355     0          116          0.903     1           37.836        0.372       1980         20           0
CHP-hc-n-O400                      GEXT         COAL        0.05        0.394      0.271     0          170          0.725     1           35.283        2.196       2004         20           0
CHP-hc-n-O400_08                   GEXT         COAL        0.05        0.394      0.271     0          170          0.804     1           35.283        2.196       2004         20           0
CHP-hc-n-200-400                   GEXT         COAL        0.05        0.35       0.250     0          157          0.726     1           34.143        2.049       1980         20           0
CHP-hc-n-200-400_08                GEXT         COAL        0.05        0.35       0.250     0          157          0.804     1           34.143        2.049       1980         20           0
CHP-hc-n-U200                      GEXT         COAL        0.05        0.88       0.412     0          118          0.684     1           47.674        1.545       1980         20           0
CHP-hc-n-U200_08                   GEXT         COAL        0.05        0.88       0.412     0          118          0.758     1           47.674        1.545       1980         20           0
El-hc-nn                           GCND         COAL        0           0          0.398     0          70           0.882     1           21.893        2.192       2007         20           0
El-bc-nn                           GCND         LIGNITE     0           0          0.410     0          71           0.945     1           27.202        0.896       2005         20           0
El-gas                             GEXT         NATGAS      0.05        0.98       0.429     0          45           0.000     1           17.169        0.652       1980         20           0
Others                             GEXT         COAL        0.05        0.10       0.110     0          211          0.258     1           42.011        2.241       1980         20           0
HY-R                               GHYRR        WATER       0           0          1.000     0          0            0         1           20.000        0.000       1970         20           0
WI-S9                              GWND         WIND        0           0          1.000     0          0            0         1.35        24.300        0.000       1995         20           0
WI-L0                              GWND         WIND        0           0          1.000     0          0            0         0.608       4.920         0.000       2000         20           0
WI-S0                              GWND         WIND        0           0          1.000     0          0            0         1.08        15.550        0.000       2000         20           0
CHP_AUTO1                          GBPR         COAL        0           0.217      0.850     1.5        400          0         999         36.720        2.160       1980         20           0
CHP_AUTO2                          GBPR         FUELOIL     0           0.217      0.850     3          240          0         999         41.310        2.430       1980         20           0
CHP_AUTO3                          GBPR         NATGAS      0           0.217      0.850     2.5        240          0         999         36.720        2.160       1980         20           0
CHP_AUTO4                          GBPR         MUNIWASTE   0           0.217      0.880     6          148          0         999         82.620        2.025       1990         20           0
CHP_AUTO5                          GBPR         STRAW       0           0.217      0.880     32         128          0         999         82.620        2.025       1990         20           0
CHP_BIO                            GBPR         WOOD        0           0.217      0.880     32         128          0         999         82.620        2.025       1990         20           0
CHP_Dis_GEN                        GBPR         NATGAS      0           0.217      0.850     2.5        240          0         999         36.720        2.160       1980         20           0
HOB_AUTO1                          GHOB         COAL        0           0          0.761     0          150          0         999         3.600         1.500       1980         20           0
HOB_AUTO2                          GHOB         FUELOIL     0           0          0.850     0          150          0         999         0.900         0.750       1980         20           0
HOB_AUTO3                          GHOB         NATGAS      0           0          0.850     0          150          0         999         0.400         0.500       1980         20           0
HOB_AUTO4                          GHOB         MUNIWASTE   0           0          0.761     0          150          0         999         14.400        3.000       1980         20           0
HOB_AUTO5                          GHOB         STRAW       0           0          0.761     0          150          0         999         14.400        3.000       1980         20           0
HOB_BIO                            GHOB         STRAW       0           0          0.761     0          150          0         999         14.400        1.4         1980         20           0
HOB_Dis_GEN                        GHOB         NATGAS      0           0          0.850     0          150          0         999         0.400         1.95        1980         20           0
HO-CO                              GHOB         COAL        0           0          0.761     0          150          0         0.12        3.600         2.500       1980         20           0



* New technologies
ST-C0-LIsn                         GCND         LIGNITE     0           0          0.410     1.5        70           0.95      0.797       31.86         1.085       2000         20           1
ST-E0-LIsn                         GEXT         LIGNITE     0.15        0.7        0.410     1.5        70           0.95      0.836       33.46         1.114       2000         20           1
ST-E0-ORsn                         GEXT         ORIMULSION  0.15        0.7        0.456     3          24           0.95      0.92        36.8          1.225       2000         20           0
HO-B0-MW                           GHOB         MUNIWASTE   0           0          0.850     6          120          0         0.24        14.4          3.000       2000         20           0

*/



;

$ontext

*Multifuel units
+                                GDCOMB        GDCOMBSK      GDCOMBSLO     GDCOMBSUP
ST-Ext-L1-G                       1            1.0           0.001         1
ST-Ext-L1-O                       2            0.99          0             1

ST-Con-L2-G                       1            1.0           0.001         1
ST-Con-L2-O                       2            0.99          0             1

ST-Con-L3-G                       1            1.0           0.001         1
ST-Con-L3-O                       2            0.99          0             1
St-Con-L3-V                       2            0.99          0             1

ST-Ext-K1-G                       1            1.0           0.001         1
ST-Ext-K1-O                       2            0.99          0             1
ST-Ext-K2-G                       1            0.99          0             1
ST-Ext-K2-O                       2            0.99          0             1

ST-Ext-K1M-F4-G                   1            1.0           0.001         1
ST-Ext-K1M-F4-O                   2            0.99          0             1

ST-Ext-K2M-F5-G                   1            1.0           0.001         1
ST-Ext-K2M-F5-O                   2            0.99          0             1

ST-Ext-V31M-F2-G                  1            1.0           0.001         1
ST-Ext-V31M-F2-O                  2            0.99          0             1

ST-Ext-V32M-F3-G                  1            1.0           0.001         1
ST-Ext-V32M-F3-O                  2            0.99          0             1

ST-Ext-V3-G                       1            1.0           0.001         1
ST-Ext-V3-O                       2            0.99          0             1

ST-Cond-LM-F1-G                   1            1.0           0.001         1
ST-Cond-LM-F1-O                   2            0.99          0             1
ST-Cond-LM-F1-V                   2            0.99          0             1


*  GDCOMB            'Combination technology'
*  GDCOMBSK          'Combination technology, maximum share of capacity'
*  GDCOMBSLO         'Combination technology, minimum share of production'
*  GDCOMBSUP         'Combination technology, maximum share of production'

$offtext



* Note: the data set is not formally updated with respect to unload, load, therefore:

GDATA(GGG,'GDSTOHLOAD')$(GDATA(GGG,'GDTYPE') EQ GHSTO)= GDATA(GGG,'GDCB');
GDATA(GGG,'GDSTOHUNLD')$(GDATA(GGG,'GDTYPE') EQ GHSTO)= GDATA(GGG,'GDCV');

GDATA(GGG,'GDSTOHLOAD')$(GDATA(GGG,'GDTYPE') EQ GESTO)= GDATA(GGG,'GDCB');
GDATA(GGG,'GDSTOHUNLD')$(GDATA(GGG,'GDTYPE') EQ GESTO)= GDATA(GGG,'GDCV');

*  Note: the following integer codes for technology types will become obsolete,
*  you should always use the Acronyms for specification of type, cf. the definition:
*  ACRONYMS  GCND, GBPR ,GEXT, GHOB, GETOH, GHSTO, GESTO, GHYRS, GHYRR, GWND, GSOLE, GSOLH;
*  Old GDTYPE:
*  1 = CONDENSING            2 = BACKPRESSURE          3 = EXTRACTION
*  4 = HEATONLY BOILERS      5 = HEAT PUMPS            6 = HEAT STORAGE
*  7 = ELECTRICITY STORAGE   8 = HYDRO WITH RESERVOIR  9 = HYDRO RUN-OF-RIVER
*  10= WIND POWER           11 = SOLAR VOLT.
*  Acronyms are used in this file.


* GDFUEL:
* With respect to GDFUEL see the file fuel.inc

* GDCV:
* GDCV is relevant only for extraction units (GDTYPE GEXT),
* it should probably be in the range 0 to 0.3.
* The GDCV value is relevant only for extraction units (GDTYPE GEXT)
* and should not be filled in for other units
* (it will, however, below be set to 1 so that the fuel consumption
* for these units can be found using the same formula as for GDTYPE GCND).


* GDCB
* GDCB is relevant only for backpressure and extraction units (GDTYPE GBPR and GEXT),
* it should probably be in the range 0.1 to 1.

* GDFE:
* GDFE: Electricity efficiency for units which only produce electricity
* (GDTYPE GCND) and for extraction units (GDTYPE GEXT); total efficiency for units
* which only produce heat (GDTYPE GHOB) and for back pressure units (GDTYPE GBPR).
* For condensing units and extraction units (GDTYPE GCND and GEXT) the value should
* probably be in the range 0.4 - 0.6.
* For extraction units (GDTYPE GEXT) the connection between GDFE and the GDCV value
* shall be checked so the total efficiency does not exceed 100%.
* For back pressure units (GDTYPE GBPR) the value should probably be
* in the range 0.7 - 0.95
* For heat only units (GDTYPE GHOB) the value should probably be in
* the range 0.7 - 0.95
* For heatpumps (GDTYPE GETOH) the value should probably be between 0.9 and 4.
* For hydro (GDTYPE GHYRS, GHYRR), wind (GDTYPE GWND), solar (GDTYPE GSOLE, GSOLH): insert 1.00
