TABLE GEFFRATE(AAA,GGG)  'Reduction in fuel efficiency (fraction)'                  
*                                                                     DK_E_Rural_WI 
* DK_E_Rural                                                          1             
;                                                                                   
                                                                                    
