TABLE GEQF(YYY,CCCRRRAAA,FFF)  'Required fuel use (GJ) per year'
                                                                                                                                                         NATGAS MUNIWASTE     STRAW       WOOD        WOODWASTE
*Available Municipal Solid Waste for Incineration - data from FRIDA (TopWaste project)
2016.DK2                                                                                                                                                        14930786
2020.DK2                                                                                                                                                        15792925
2025.DK2                                                                                                                                                        14913845
2030.DK2                                                                                                                                                        14578805
2035.DK2                                                                                                                                                        15247736
2040.DK2                                                                                                                                                        15958369
2045.DK2                                                                                                                                                        16824593
2050.DK2                                                                                                                                                        17852682
2016.DK1                                                                                                                                                        17854860
2020.DK1                                                                                                                                                        18498716
2025.DK1                                                                                                                                                        17224389
2030.DK1                                                                                                                                                        16724144
2035.DK1                                                                                                                                                        17377630
2040.DK1                                                                                                                                                        18212433
2045.DK1                                                                                                                                                        19226856
2050.DK1                                                                                                                                                        20428718
*Municipal Solid Waste for Incineration in the rest of Europe (TopWaste Project) - except Germany where the current level is used as level towards 2050.
2016.FINLAND                                                                                                                                                    25159042
2016.SWEDEN                                                                                                                                                     48582978
2016.GERMANY                                                                                                                                                    57600000
2016.NORWAY                                                                                                                                                     14545173
2020.FINLAND                                                                                                                                                    27186342
2020.GERMANY                                                                                                                                                    57600000
2020.NORWAY                                                                                                                                                     14545173
2020.SWEDEN                                                                                                                                                     52497763
2025.FINLAND                                                                                                                                                    29000000
2025.GERMANY                                                                                                                                                    57600000
2025.NORWAY                                                                                                                                                     19410434
2025.SWEDEN                                                                                                                                                     56000000
2030.FINLAND                                                                                                                                                    29000000
2030.GERMANY                                                                                                                                                    57600000
2030.NORWAY                                                                                                                                                     24275695
2030.SWEDEN                                                                                                                                                     56000000
2035.FINLAND                                                                                                                                                    29000000
2035.GERMANY                                                                                                                                                    57600000
2035.NORWAY                                                                                                                                                     24275695
2035.SWEDEN                                                                                                                                                     56000000
2040.FINLAND                                                                                                                                                    29000000
2040.GERMANY                                                                                                                                                    57600000
2040.NORWAY                                                                                                                                                     24275695
2040.SWEDEN                                                                                                                                                     56000000
2045.FINLAND                                                                                                                                                    29000000
2045.GERMANY                                                                                                                                                    57600000
2045.NORWAY                                                                                                                                                     24275695
2045.SWEDEN                                                                                                                                                     56000000
2050.FINLAND                                                                                                                                                    29000000
2050.GERMANY                                                                                                                                                    57600000
2050.NORWAY                                                                                                                                                     24275695
2050.SWEDEN                                                                                                                                                     56000000
*
$ontext
*Data TopWaste Project - HAZARDOUSWASTE
2016.DENMARK
2020.DENMARK
2025.DENMARK
2030.DENMARK
2035.DENMARK
2040.DENMARK
2045.DENMARK
2050.DENMARK
$offtext

;
