TABLE FDATA(FFF,FDATASET)   'Fuel specific values'                                                                                                   
* PARAMETER FDATA contains information about emission characteristics of fuels.                                                                      
* In addition it contains a name (FDACRONYM) for the fuel, note that this must be as an ACRONYM previously.                                          
* Note: So far values just copied from BIOGAS from FDATA                                                                                             
                                                                                                                                                     
                                                                                                            FDACRONYM   FDCO2 FDSO2 FDN2O  !!   FDCO2
*                                                                                                           Units       kg/GJ kg/GJ kg/GJ            
HYDROGEN                                                                                                    HYDROGEN                                 
BIOGAS_H2                                                                                                   BIOGAS_H2   0     0.025 0.004            
THERMGAS_H2                                                                                                 THERMGAS_H2 0     0.025 0.004            
;                                                                                                                                                    
