SET HYRSDATASET  'Characteristics of hydro reservoirs'                                               
* AGT: added one more constraint - maximum hydro production                                          
/                                                                                                    
HYRSMINVOL   'Minimum reservoir filling (MWh weekly production/MW total capacity)'                   
HYRSMAXVOL   'Maximum reservoir filling at start of season (MWh weekly production/MW total capacity)'
HYRSDGMIN    'Minimum hydro production (MWh weekly production/MW total capacity)'                    
HYRSDGMAX    'Maximum hydro production (MWh weekly production/MW total capacity)'                    
/;                                                                                                   
