TABLE M_POLNA(YYY,MPOLSET)  "Emission policy data; default for the 'LIM_' entries: 0 implies irrelevant, EPS implies no emission permitted (aggerated countries)"                                      
                                                                                                                                                                                                       
*                                                                                                                                                                 LIM_CO2    LIM_SO2    LIM_NOX        
* Units:                                                                                                                                                          t CO2/year t SO2/year t NOx/year     
*2012                                                                                                                                                                                                  
;                                                                                                                                                                                                      
