* File Mpol.inc

* This file is part of the Balmorel model, version 2.10 Alpha (October 2002).

* User: Rasmus Boeg

* File modified and saved 29-9-2004 17:15

*------------------------------------------------------------------------------

* EMISSION POLICY -------------------------------------------------------------


* PARAMETER MPOL_Y contains emissions policy data.

* Data sources:
* New data from Estonia and Poland.
* No real data entered, as this is policy specific.

* Units: (See table)
TABLE M_POL(YYY,MPOLSET,CCC)  'Emission policy data'

           LIM_CO2.DENMARK        LIM_SO2.DENMARK        LIM_NOX.DENMARK
* Units:   t CO2/year               t SO2/year               t NOx/year
1995       INF                      INF                      INF
1996       INF                      INF                      INF
1997       INF                      INF                      INF
1998       INF                      INF                      INF
1999       INF                      INF                      INF
2000       INF                      INF                      INF
2001       INF                      INF                      INF
2002       INF                      INF                      INF
2003       INF                      INF                      INF
2004       INF                      INF                      INF
2005       INF                      INF                      INF
2006       INF                      INF                      INF
2007       INF                      INF                      INF
2008       INF                      INF                      INF
2009       INF                      INF                      INF
2010       INF                      INF                      INF
2011       INF                      INF                      INF
2012       INF                      INF                      INF
2013       INF                      INF                      INF
2014       INF                      INF                      INF
2015       INF                      INF                      INF
2016       INF                      INF                      INF
2017       INF                      INF                      INF
2018       INF                      INF                      INF
2019       INF                      INF                      INF
2020       INF                      INF                      INF
2021       INF                      INF                      INF
2022       INF                      INF                      INF
2023       INF                      INF                      INF
2024       INF                      INF                      INF
2025       INF                      INF                      INF
2026       INF                      INF                      INF
2027       INF                      INF                      INF
2028       INF                      INF                      INF
2029       INF                      INF                      INF
2030       INF                      INF                      INF

+          TAX_CO2.DENMARK        TAX_SO2.DENMARK        TAX_NOX.DENMARK
* Units:   EUR90/t CO2              EUR90/t SO2              EUR90/t NOx
1995       0                        988
1996       0                        988
1997       0                        988
1998       0                        988
1999       0                        988
2000       0                        988
2001       0                        988
2002       0                        988
2003       0                        988
2004       0                        988
2005       14.39                    988
2006       14.39                    988
2007       14.39                    988
2008       14.39                    988
2009       14.39                    988
2010       14.39                    988
2011       14.39                    988
2012       14.39                    988
2013       14.39                    988
2014       14.39                    988
2015       14.39                    988
2016       14.39                    988
2017       14.39                    988
2018       14.39                    988
2019       14.39                    988
2020       14.39                    988
2021       14.39                    988
2022       14.39                    988
2023       14.39                    988
2024       14.39                    988
2025       14.39                    988
2026       14.39                    988
2027       14.39                    988
2028       14.39                    988
2029       14.39                    988
2030       14.39                    988

+          LIM_CO2.FINLAND          LIM_SO2.FINLAND          LIM_NOX.FINLAND
* Units:   t CO2/year               t SO2/year               t NOx/year
1995       INF                      INF                      INF
1996       INF                      INF                      INF
1997       INF                      INF                      INF
1998       INF                      INF                      INF
1999       INF                      INF                      INF
2000       INF                      INF                      INF
2001       INF                      INF                      INF
2002       INF                      INF                      INF
2003       INF                      INF                      INF
2004       INF                      INF                      INF
2005       INF                      INF                      INF
2006       INF                      INF                      INF
2007       INF                      INF                      INF
2008       INF                      INF                      INF
2009       INF                      INF                      INF
2010       INF                      INF                      INF
2011       INF                      INF                      INF
2012       INF                      INF                      INF
2013       INF                      INF                      INF
2014       INF                      INF                      INF
2015       INF                      INF                      INF
2016       INF                      INF                      INF
2017       INF                      INF                      INF
2018       INF                      INF                      INF
2019       INF                      INF                      INF
2020       INF                      INF                      INF
2021       INF                      INF                      INF
2022       INF                      INF                      INF
2023       INF                      INF                      INF
2024       INF                      INF                      INF
2025       INF                      INF                      INF
2026       INF                      INF                      INF
2027       INF                      INF                      INF
2028       INF                      INF                      INF
2029       INF                      INF                      INF
2030       INF                      INF                      INF

+          TAX_CO2.FINLAND          TAX_SO2.FINLAND          TAX_NOX.FINLAND
* Units:   EUR90/t CO2              EUR90/t SO2              EUR90/t NOx
1995       0                        0                        0
1996       0                        0                        0
1997       0                        0                        0
1998       0                        0                        0
1999       0                        0                        0
2000       0                        0                        0
2001       0                        0                        0
2002       0                        0                        0
2003       0                        0                        0
2004       0                        0                        0
2005       14.39                    0                        0
2006       14.39                    0                        0
2007       14.39                    0                        0
2008       14.39                    0                        0
2009       14.39                    0                        0
2010       14.39                    0                        0
2011       14.39                    0                        0
2012       14.39                    0                        0
2013       14.39                    0                        0
2014       14.39                    0                        0
2015       14.39                    0                        0
2016       14.39                    0                        0
2017       14.39                    0                        0
2018       14.39                    0                        0
2019       14.39                    0                        0
2020       14.39                    0                        0
2021       14.39                    0                        0
2022       14.39                    0                        0
2023       14.39                    0                        0
2024       14.39                    0                        0
2025       14.39                    0                        0
2026       14.39                    0                        0
2027       14.39                    0                        0
2028       14.39                    0                        0
2029       14.39                    0                        0
2030       14.39                    0                        0

+          LIM_CO2.GERMANY          LIM_SO2.GERMANY          LIM_NOX.GERMANY
* Units:   t CO2/year               t SO2/year               t NOx/year
1995       INF                      INF                      INF
1996       INF                      INF                      INF
1997       INF                      INF                      INF
1998       INF                      INF                      INF
1999       INF                      INF                      INF
2000       INF                      INF                      INF
2001       INF                      INF                      INF
2002       INF                      INF                      INF
2003       INF                      INF                      INF
2004       INF                      INF                      INF
2005       INF                      INF                      INF
2006       INF                      INF                      INF
2007       INF                      INF                      INF
2008       INF                      INF                      INF
2009       INF                      INF                      INF
2010       INF                      INF                      INF
2011       INF                      INF                      INF
2012       INF                      INF                      INF
2013       INF                      INF                      INF
2014       INF                      INF                      INF
2015       INF                      INF                      INF
2016       INF                      INF                      INF
2017       INF                      INF                      INF
2018       INF                      INF                      INF
2019       INF                      INF                      INF
2020       INF                      INF                      INF
2021       INF                      INF                      INF
2022       INF                      INF                      INF
2023       INF                      INF                      INF
2024       INF                      INF                      INF
2025       INF                      INF                      INF
2026       INF                      INF                      INF
2027       INF                      INF                      INF
2028       INF                      INF                      INF
2029       INF                      INF                      INF
2030       INF                      INF                      INF

+          TAX_CO2.GERMANY          TAX_SO2.GERMANY          TAX_NOX.GERMANY
* Units:   EUR90/t CO2              EUR90/t SO2              EUR90/t NOx
1995       0                        0                        0
1996       0                        0                        0
1997       0                        0                        0
1998       0                        0                        0
1999       0                        0                        0
2000       0                        0                        0
2001       0                        0                        0
2002       0                        0                        0
2003       0                        0                        0
2004       0                        0                        0
2005       14.39                    0                        0
2006       14.39                    0                        0
2007       14.39                    0                        0
2008       14.39                    0                        0
2009       14.39                    0                        0
2010       14.39                    0                        0
2011       14.39                    0                        0
2012       14.39                    0                        0
2013       14.39                    0                        0
2014       14.39                    0                        0
2015       14.39                    0                        0
2016       14.39                    0                        0
2017       14.39                    0                        0
2018       14.39                    0                        0
2019       14.39                    0                        0
2020       14.39                    0                        0
2021       14.39                    0                        0
2022       14.39                    0                        0
2023       14.39                    0                        0
2024       14.39                    0                        0
2025       14.39                    0                        0
2026       14.39                    0                        0
2027       14.39                    0                        0
2028       14.39                    0                        0
2029       14.39                    0                        0
2030       14.39                    0                        0

+          LIM_CO2.NORWAY           LIM_SO2.NORWAY           LIM_NOX.NORWAY
* Units:   t CO2/year               t SO2/year               t NOx/year
1995       INF                      INF                      INF
1996       INF                      INF                      INF
1997       INF                      INF                      INF
1998       INF                      INF                      INF
1999       INF                      INF                      INF
2000       INF                      INF                      INF
2001       INF                      INF                      INF
2002       INF                      INF                      INF
2003       INF                      INF                      INF
2004       INF                      INF                      INF
2005       INF                      INF                      INF
2006       INF                      INF                      INF
2007       INF                      INF                      INF
2008       INF                      INF                      INF
2009       INF                      INF                      INF
2010       INF                      INF                      INF
2011       INF                      INF                      INF
2012       INF                      INF                      INF
2013       INF                      INF                      INF
2014       INF                      INF                      INF
2015       INF                      INF                      INF
2016       INF                      INF                      INF
2017       INF                      INF                      INF
2018       INF                      INF                      INF
2019       INF                      INF                      INF
2020       INF                      INF                      INF
2021       INF                      INF                      INF
2022       INF                      INF                      INF
2023       INF                      INF                      INF
2024       INF                      INF                      INF
2025       INF                      INF                      INF
2026       INF                      INF                      INF
2027       INF                      INF                      INF
2028       INF                      INF                      INF
2029       INF                      INF                      INF
2030       INF                      INF                      INF

+          TAX_CO2.NORWAY           TAX_SO2.NORWAY           TAX_NOX.NORWAY
* Units:   EUR90/t CO2              EUR90/t SO2              EUR90/t NOx
1995       0                        1482                     0
1996       0                        1482                     0
1997       0                        1482                     0
1998       0                        1482                     0
1999       0                        1482                     0
2000       0                        1482                     0
2001       0                        1482                     0
2002       0                        1482                     0
2003       0                        1482                     0
2004       0                        1482                     0
2005       14.39                    1482                     0
2006       14.39                    1482                     0
2007       14.39                    1482                     0
2008       14.39                    1482                     0
2009       14.39                    1482                     0
2010       14.39                    1482                     0
2011       14.39                    1482                     0
2012       14.39                    1482                     0
2013       14.39                    1482                     0
2014       14.39                    1482                     0
2015       14.39                    1482                     0
2016       14.39                    1482                     0
2017       14.39                    1482                     0
2018       14.39                    1482                     0
2019       14.39                    1482                     0
2020       14.39                    1482                     0
2021       14.39                    1482                     0
2022       14.39                    1482                     0
2023       14.39                    1482                     0
2024       14.39                    1482                     0
2025       14.39                    1482                     0
2026       14.39                    1482                     0
2027       14.39                    1482                     0
2028       14.39                    1482                     0
2029       14.39                    1482                     0
2030       14.39                    1482                     0

+          LIM_CO2.SWEDEN           LIM_SO2.SWEDEN           LIM_NOX.SWEDEN
* Units:   t CO2/year               t SO2/year               t NOx/year
1995       INF                      INF                      INF
1996       INF                      INF                      INF
1997       INF                      INF                      INF
1998       INF                      INF                      INF
1999       INF                      INF                      INF
2000       INF                      INF                      INF
2001       INF                      INF                      INF
2002       INF                      INF                      INF
2003       INF                      INF                      INF
2004       INF                      INF                      INF
2005       INF                      INF                      INF
2006       INF                      INF                      INF
2007       INF                      INF                      INF
2008       INF                      INF                      INF
2009       INF                      INF                      INF
2010       INF                      INF                      INF
2011       INF                      INF                      INF
2012       INF                      INF                      INF
2013       INF                      INF                      INF
2014       INF                      INF                      INF
2015       INF                      INF                      INF
2016       INF                      INF                      INF
2017       INF                      INF                      INF
2018       INF                      INF                      INF
2019       INF                      INF                      INF
2020       INF                      INF                      INF
2021       INF                      INF                      INF
2022       INF                      INF                      INF
2023       INF                      INF                      INF
2024       INF                      INF                      INF
2025       INF                      INF                      INF
2026       INF                      INF                      INF
2027       INF                      INF                      INF
2028       INF                      INF                      INF
2029       INF                      INF                      INF
2030       INF                      INF                      INF

+          TAX_CO2.SWEDEN           TAX_SO2.SWEDEN           TAX_NOX.SWEDEN
* Units:   EUR90/t CO2              EUR90/t SO2              EUR90/t NOx
1995       0                        1215                     0
1996       0                        1215                     0
1997       0                        1215                     0
1998       0                        1215                     0
1999       0                        1215                     0
2000       0                        1215                     0
2001       0                        1215                     0
2002       0                        1215                     0
2003       0                        1215                     0
2004       0                        1215                     0
2005       14.39                    1215                     0
2006       14.39                    1215                     0
2007       14.39                    1215                     0
2008       14.39                    1215                     0
2009       14.39                    1215                     0
2010       14.39                    1215                     0
2011       14.39                    1215                     0
2012       14.39                    1215                     0
2013       14.39                    1215                     0
2014       14.39                    1215                     0
2015       14.39                    1215                     0
2016       14.39                    1215                     0
2017       14.39                    1215                     0
2018       14.39                    1215                     0
2019       14.39                    1215                     0
2020       14.39                    1215                     0
2021       14.39                    1215                     0
2022       14.39                    1215                     0
2023       14.39                    1215                     0
2024       14.39                    1215                     0
2025       14.39                    1215                     0
2026       14.39                    1215                     0
2027       14.39                    1215                     0
2028       14.39                    1215                     0
2029       14.39                    1215                     0
2030       14.39                    1215                     0
;


$ifi not %CO2HIGH%==yes M_POL(YYY,'TAX_CO2',CCC)=0;
$ifi %CO2EURO10%==yes M_POL(YYY,'TAX_CO2',CCC)=0;
$ifi %CO2EURO40%==yes M_POL(YYY,'TAX_CO2',CCC)=0;

$ifi %CO2EURO10%==yes M_POL(YYY,'TAX_CO2',CCC)$(YVALUE(YYY) ge 2006)=10/1.389;
$ifi %CO2EURO30%==yes M_POL(YYY,'TAX_CO2',CCC)$(YVALUE(YYY) ge 2006)=30/1.389;
$ifi %CO2EURO40%==yes M_POL(YYY,'TAX_CO2',CCC)$(YVALUE(YYY) ge 2006)=40/1.389;

* Emission limits values not assigned a positive level in the table above.
* are here given the default value INF:

M_POL(Y,'LIM_CO2',C)$(M_POL(Y,'LIM_CO2',C) EQ 0) = INF;
M_POL(Y,'LIM_SO2',C)$(M_POL(Y,'LIM_SO2',C) EQ 0) = INF;
M_POL(Y,'LIM_NOX',C)$(M_POL(Y,'LIM_NOX',C) EQ 0) = INF;