SET MPOLSET  'Emission and other policy data'
/                                            
TAX_CO2  'CO2 emission tax (Euro/t CO2)'     
TAX_SO2  'SO2 emission tax (Euro/t SO2)'     
TAX_NOx  'NOx emission tax (Euro/kg NOx)'    
LIM_CO2  'Annual CO2 limit (t CO2/year)'     
LIM_SO2  'Annual SO2 limit (t SO2/year)'     
LIM_NOx  'Annual NOx limit(kg NOx/year)'     
/;                                           
