* Specification of areas in regions:

SET RRRAAA(RRR,AAA)  'Areas in region'
/
  DK_E.(DK_E_Urban,DK_E_Rural, DK_E_1,  DK_E_2,  DK_E_3,  DK_E_4,  DK_E_5,DK_E_Offshore)
  DK_W.(DK_W_Urban,DK_W_Rural, DK_W_1,  DK_W_2,  DK_W_3,  DK_W_4,  DK_W_5,  DK_W_6, DK_W_AALBORG, DK_W_AARHUS, DK_W_TREFOR, DK_W_ODENSE, DK_W_Offshore)
  EE_R.(EE_R_Urban,EE_R_Rural)
  FI_R.(FI_R_Decen,FI_R_Urban,FI_R_Rural,FI_R_Offshore)
  DE_CS.(DE_CS_A1)
  DE_NE.(DE_NE_A1, DE_NE_Offshore)
  DE_NW.(DE_NW_A1, DE_NW_Offshore)
  LV_R.(LV_R_Urban,LV_R_Rural)
  LT_R.(LT_R_Urban,LT_R_Rural)
  NO_N.(NO_N_Rural, NO_N_Offshore)
  NO_M.(NO_M_Rural, NO_M_Offshore)
  NO_S.(NO_S_Rural, NO_S_Offshore)
  NO_O.(NO_O_Rural)
  PL_R.(PL_R_Urban,PL_R_Rural)
  RU_W.(RU_W_Urban,RU_W_Rural)
  RU_K.(RU_K_Urban,RU_K_Rural)
  SE_N.(SE_N_Rural, SE_N_Bio, SE_N_Offshore)
  SE_M.(SE_M_Urban, SE_M_Rural, SE_M_Bio, SE_M_Offshore)
  SE_S.(SE_S_Rural, SE_S_Bio, SE_S_Offshore)
/;