* PARAMETER SOLE_VAR_T contains the description of seasonal and daily variation
* of the solar power production.
* Units: (none)

* Data source:


* ------------------------------------------------------------------------------

PARAMETER  SOLE_VAR_T(AAA,SSS,TTT) 'Variation of the solar generation'  /
DK_E_Rural.S01.T001    1 /; /*dummydata!*/

* ------------------------------------------------------------------------------



