* PARAMETER SOLHFLH holds the yearly number of full load hours for solar heat.
* Unit: hours.

PARAMETER SOLHFLH(AAA)  'Full load hours for solar power (hours)'
* NOT REAL DATA, DEMONSTRATION ONLY
/
DK_E_Rural                    2500
DK_W_Rural                    2500
EE_R_Rural                    2500
FI_R_Rural                    2500
DE_CS_A1                      2500
DE_NE_A1                      2500
DE_NW_A1                      2500
*LV_R_Rural                    2500
*LT_R_Rural                    2500
NO_N_Rural                    2500
NO_M_Rural                    2500
NO_S_Rural                    2500
NO_O_Rural                    2500
PL_R_Rural                    2500
RU_W_Rural                    2500
RU_K_Rural                    2500
SE_N_Rural                    2500
SE_M_Rural                    2500
SE_S_Rural                    2500
/;
