* PARAMETER SOLH_VAR_T contains the description of seasonal and daily variation
* of the solar heat production.
* Units: (none)


* ------------------------------------------------------------------------------

PARAMETER  SOLH_VAR_T(AAA,SSS,TTT) 'Variation of the solar heat generation'  /
DK_E_Rural.S01.T001    1 /; /*dummydata!*/


* ------------------------------------------------------------------------------
