PARAMETER TAX_F(FFF,CCC) 'Fuel taxes for heat and electricity production (Money/GJ)'     
/                                                                                        
ELECTRIC  .              DENMARK                                                     7   
ELECTRIC  .              NORWAY                                                      7   
ELECTRIC  .              SWEDEN                                                      7   
ELECTRIC  .              GERMANY                                                     7   
ELECTRIC  .              FINLAND                                                     7   
ELECTRIC  .              NETHERLANDS                                                 7   
ELECTRIC  .              UNITED_KINGDOM                                              7   
ELECTRIC  .              ESTONIA                                                     7   
ELECTRIC  .              LATVIA                                                      7   
ELECTRIC  .              LITHUANIA                                                   7   
ELECTRIC  .              POLAND                                                      7   
NATGAS    .              DENMARK                                                     0.2 
NATGAS    .              NORWAY                                                      0.2 
NATGAS    .              SWEDEN                                                      0.2 
NATGAS    .              GERMANY                                                     0.2 
NATGAS    .              FINLAND                                                     0.2 
NATGAS    .              NETHERLANDS                                                 0.2 
NATGAS    .              UNITED_KINGDOM                                              0.2 
NATGAS    .              ESTONIA                                                     0.2 
NATGAS    .              LATVIA                                                      0.2 
NATGAS    .              LITHUANIA                                                   0.2 
NATGAS    .              POLAND                                                      0.2 
/;                                                                                       
