PARAMETER TAX_GE(YYY,AAA,G) 'Electricity taxes(+) and subsidies(-) on generation units (Money/MWh)'  
                                                                                                     
/                                                                                                    
/;                                                                                                   
