PARAMETER TAX_DH(CCC,DHUSER) 'Consumers tax on heat consumption (Money/MWh)'  
/                                                                             
$ontext                                                                       
DENMARK   0                                                                   
ESTONIA   0                                                                   
FINLAND   0                                                                   
GERMANY   0                                                                   
LATVIA    0                                                                   
LITHUANIA 0                                                                   
NORWAY    0                                                                   
POLAND    0                                                                   
RUSSIA    0                                                                   
SWEDEN    0                                                                   
BELARUS   0                                                                   
ESTONIA   0                                                                   
LATVIA    0                                                                   
LITHUANIA 0                                                                   
POLAND    0                                                                   
$offtext                                                                      
/;                                                                            
