PARAMETER WAVEFLH(AAA)  'Full load hours for wave power (hours)'     
* NOT REAL DATA, DEMONSTRATION ONLY.                                 
/                                                                    
DK2_Medium                                                       816 
DK2_Rural                                                        816 
DK1_MedSmall                                                     816 
DK1_Rural                                                        816 
                                                                     
FinA                                                             1040
DE4-E_A                                                          1040
DE4-N_A                                                          1040
DE4-S_A                                                          1040
DE4-W_A                                                          1040
NL_A                                                             1040
NO1_A1                                                           1040
NO2_A1                                                           1040
NO3_A1                                                           1040
NO4_A1                                                           1040
NO5_A1                                                           1040
SE1A                                                             1040
SE2A                                                             1040
SE3A                                                             1040
SE4A                                                             1040
UK_A                                                             1040
EE_A                                                             1040
LV_A                                                             1040
LT_A                                                             1040
/;                                                                   
