* PARAMETER WNDFLH holds the yearly number of full load hours for wind power.
* Unit: hours.

* Source: Reanalysis data "Egualizing Effects of the Wind Energy Production in the
* Northern Europe Determined from Reanalysis Data", Risoe-R-1182(EN)

PARAMETER WNDFLH(AAA)  'Full load hours for wind power (hours)'
/
DK_W_Rural        1982
DK_W_Offshore     4145
DK_E_Rural        1696
DK_E_Offshore     3330
DK_E_Urban        2500
DK_W_Urban        2500
NO_S_Rural        3000
SE_M_Rural        2800
NO_M_Rural        3000
FI_R_Rural        2650
NO_N_Rural        3000
SE_S_Rural        2800
SE_N_Rural        2800
DE_NW_Offshore    3300
DE_NE_Offshore    3300
DE_NW_A1          1700
DE_NE_A1          1696
DE_CS_A1          1696
/;
