* PARAMETER WTRRRSFLH holds the yearly number of full load hours for hydro with seasonal storage.
* Unit: hours.
* Average inflow over 10 years - normal year (updated from Nordel Annual report 2006)
PARAMETER WTRRSFLH(AAA)  'Full load hours for hydro reservoir plants (Hours)'
/
DK_E_Rural                    3000
DK_W_Rural                    3000
EE_R_Rural                    3000
FI_R_Rural                    4310
DE_CS_A1                      1000
DE_NE_A1                      1000
DE_NW_A1                      1000
LV_R_Rural                    3000
LT_R_Rural                    3000
NO_N_Rural                    4501
NO_M_Rural                    4549
NO_S_Rural                    4017
NO_O_Rural                    4200
PL_R_Rural                    3000
RU_W_Rural                    3000
RU_K_Rural                    3000
SE_N_Rural                    3860
SE_M_Rural                    4256
SE_S_Rural                    4058
/;

* Note: files for 'wet' and 'dry' hydrological years (based on analysis of the above source) have been made as well.

