PARAMETER WTRRRFLH(AAA) 'Full load hours for hydro run-of-river plants (hours)'                                              
* Includes the three options "dry", "wet" and "normal" according to which hydrological conditions to analyze                 
/                                                                                                                            
* Average year 2002-2011                                                                                                     
FinA                                                                                                         4819.27012282765
DE4-E_A                                                                                                      4819.86064070176
DE4-N_A                                                                                                      4820            
DE4-S_A                                                                                                      4820            
DE4-W_A                                                                                                      4820            
NL_A                                                                                                         4200            
NO1_A1                                                                                                       4175.15822434474
NO2_A1                                                                                                       4734.04616878191
NO3_A1                                                                                                       3856.64552610268
NO4_A1                                                                                                       3844.41878371575
NO5_A1                                                                                                       5285.48782040366
SE1A                                                                                                         4117.721607607  
SE2A                                                                                                         5120.45007111377
SE3A                                                                                                         4202.55103738896
SE4A                                                                                                         4772.87790539999
UK_A                                                                                                         3032.18920765027
EE_Rural                                                                                                     7500            
LV_RigaR                                                                                                     2465            
LT_KauU                                                                                                      4800            
PL_Rural                                                                                                     2425            
DK2_NoDH                                                                                                     4819.86064070176
DK1_NoDH                                                                                                     4819.86064070176
/;                                                                                                                           
