* PARAMETER WTRRRRFLH holds the yearly number of full load hours for hydro run-of-river.
* Unit: hours.

PARAMETER WTRRRFLH(AAA)  'Full load hours for hydro run-of-river plants (hours)'
/
DK_E_Rural                    3000
DK_W_Rural                    3000
EE_R_Rural                    3000
FI_R_Rural                    3000
DE_CS_A1                      1000
DE_NE_A1                      1000
DE_NW_A1                      1000
LV_R_Rural                    3000
LT_R_Rural                    3000
NO_N_Rural                    3000
NO_M_Rural                    3000
NO_S_Rural                    3000
NO_O_Rural                    3000
PL_R_Rural                    3000
RU_W_Rural                    3000
RU_K_Rural                    3000
SE_N_Rural                    3000
SE_M_Rural                    3000
SE_S_Rural                    3000
/;
