PARAMETER XKRATE  "Transmission capacity rating (share; non-negative, typically close to 1; default/1/, use eps for 0)";                                                            
TABLE XKRATE(IRRRE,IRRRI,SSS,TTT)                                                                                                                                                   
                                                                                                                                                                                    
;                                                                                                                                                                                   
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
XKRATE(IRRRE,IRRRI,S,T)$((XKRATE(IRRRE,IRRRI,S,T) EQ 0) and (SUM(Y,(XKINI(Y,IRRRE,IRRRI)))))= 0.9;                                                                                  
