PARAMETER XMAXINV(IRRRE,IRRRI)   'Max investment in transmission capacity between two regions for each simulated year(each 5th year)'                           
                                                                                                                                                                
/                                                                                                                                                               
$ontext                                                                                                                                                         
DK_E                                                                                                                                  .    DK_W  1000           
DK_E                                                                                                                                  .    DE_NE 1000           
DK_E                                                                                                                                  .    NO_O  3000           
DK_E                                                                                                                                  .    SE_S  1000           
DK_W                                                                                                                                  .    DK_E  1000           
DK_W                                                                                                                                  .    DE_NW 2000           
DK_W                                                                                                                                  .    NO_S  1000           
DK_W                                                                                                                                  .    SE_M  1000           
DE_CS                                                                                                                                 .    DE_NE 12000          
DE_CS                                                                                                                                 .    DE_NW 12000          
DE_NE                                                                                                                                 .    DE_CS 12000          
DE_NE                                                                                                                                 .    DE_NW 12000          
DE_NE                                                                                                                                 .    DK_E  1000           
DE_NE                                                                                                                                 .    SE_S  1000           
DE_NW                                                                                                                                 .    DE_CS 12000          
DE_NW                                                                                                                                 .    DE_NE 12000          
DE_NW                                                                                                                                 .    DK_W  2000           
DE_NW                                                                                                                                 .    NO_S  2000           
DE_NW                                                                                                                                 .    SE_S  1000           
FI_R                                                                                                                                  .    NO_N  1000           
FI_R                                                                                                                                  .    SE_M  2000           
FI_R                                                                                                                                  .    SE_N  2000           
NO_M                                                                                                                                  .    NO_S  2000           
NO_M                                                                                                                                  .    NO_N  2000           
NO_M                                                                                                                                  .    SE_N  2000           
NO_N                                                                                                                                  .    FI_R  1000           
NO_N                                                                                                                                  .    NO_M  2000           
NO_N                                                                                                                                  .    SE_N  2000           
NO_O                                                                                                                                  .    DK_E  3000           
NO_O                                                                                                                                  .    SE_M  2000           
NO_O                                                                                                                                  .    NO_S  9000           
NO_S                                                                                                                                  .    DE_NW 2000           
NO_S                                                                                                                                  .    DK_W  1000           
NO_S                                                                                                                                  .    NO_M  2000           
NO_S                                                                                                                                  .    NO_O  9000           
SE_M                                                                                                                                  .    DK_W  1000           
SE_M                                                                                                                                  .    FI_R  2000           
SE_M                                                                                                                                  .    SE_N  2000           
SE_M                                                                                                                                  .    SE_S  2000           
SE_M                                                                                                                                  .    NO_O  2000           
SE_N                                                                                                                                  .    FI_R  2000           
SE_N                                                                                                                                  .    NO_M  2000           
SE_N                                                                                                                                  .    NO_N  2000           
SE_N                                                                                                                                  .    SE_M  2000           
SE_S                                                                                                                                  .    DE_NE 1000           
SE_S                                                                                                                                  .    DE_NW 1000           
SE_S                                                                                                                                  .    DK_E  1000           
SE_S                                                                                                                                  .    SE_M  1000           
$offtext                                                                                                                                                        
/;                                                                                                                                                              
                                                                                                                                                                
