SETS
LIMITSFORFUELS_NUMCONMAX  'Sets in which a combination of maxima are set'
LIMITSFORFUELS_GMAXFSET(LIMITSFORFUELS_NUMCONMAX,CCCRRRAAA,FFF) 'Sets of which a combination of maxima are set'
LIMITSFORFUELS_VGFMAXSET(LIMITSFORFUELS_NUMCONMAX,CCCRRRAAA,FFF) 'Sets of which a combination of maxima are set'
LIMITSFORFUELS_NUMCONMIN  'Sets in which a combination of minima are set'
LIMITSFORFUELS_GMINFSET(LIMITSFORFUELS_NUMCONMIN,CCCRRRAAA,FFF) 'Sets of which a combination of minima are set'
LIMITSFORFUELS_VGFMINSET(LIMITSFORFUELS_NUMCONMIN,CCCRRRAAA,FFF) 'Sets of which a combination of minima are set'
;