$ifi %GAS%==yes QCONSUMPTION
QEEQ
QESTOLOADT
QESTOVOLT
*QGCBGBPR
*QGCBGEXT
*QGCVGEXT
*QGE2LEVEL
$ifi %GAS%==yes QGEQ
*QGGETOH
$ifi %GAS%==yes QGSFXW
$ifi %GAS%==yes QGSVERIGE
QHEQ
*QHSTOLOADT
*QHSTOVOLT
QHYFXRW
QOBJ
$ifi %GAS%==yes QStoreExt
$ifi %GAS%==yes QStoreInj
$ifi %GAS%==yes QTransEntryCap
$ifi %GAS%==yes QTransExitCap
QXK
VDHF_T
$ifi %GAS%==yes VEXP
$ifi %GAS%==yes VEXT
*VGE2LEVEL
VGE_T
VGH_T
VDEF_T
VDHF_T
$ifi %GAS%==yes VGUD
VHSTOLOADT
VHSTOVOLT
$ifi %GAS%==yes VINJ
VOBJ
VQEEQ
VQHEQ
VQHSTOVOLT
$ifi %GAS%==yes VSUP
$ifi %GAS%==yes VTC_EN_D
$ifi %GAS%==yes VTC_EN_W
$ifi %GAS%==yes VTC_EX_D
$ifi %GAS%==yes VTC_EX_W
$ifi %X3V%==yes VX3VEX_T
$ifi %X3V%==yes VX3VIM_T
VX_T
$ifi %CAES%==yes VCAESCOMPRESS
$ifi %CAES%==yes VCAESSTORAGE
$ifi %CAES%==yes VCAESWITHDRAW
$ifi %CAES%==yes QCAESBalance
$ifi %CAES%==yes QCAESWithdraw

;