* File apkndiscset.inc with addon apkndisc for the OptiWaste model.

SET APKNDISC_AP(AAA,PROC) "Areas for possible location of discrete capacity investments in Processes (addon apkndisc)";
SET APKNDISCSIZESET     "Set of possible sizes for discrete capacity investments in Processes (addon apkndisc)";
SET APKNDISCDATASET     "Processes investment data types for discrete capacity size investments (addon apkndisc)";
PARAMETER APKNDISCDATA(PROC,APKNDISCSIZESET,APKNDISCDATASET) "Investment data for discrete Process capacity size investments (addon apkndisc)";
