[workspace]
authors = ["mathias157 <mathiasros@proton.me>"]
channels = ["conda-forge"]
name = "BALMOREL"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
analyse = "python analysis/analyse.py "

[dependencies]
python = ">=3.14.3,<3.15"
premailer = ">=3.10.0,<4"
click = ">=8.3.1,<9"
python-decouple = ">=3.8,<4"

[pypi-dependencies]
pybalmorel = ">=0.6.0, <0.7"

[activation.env]
GAMS_SYSTEM_DIR = "/appl/gams/47.6.0"

