[workspace]
authors = ["mathias157 <mathiasros@proton.me>"]
channels = ["conda-forge"]
name = "BALMOREL"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
analyse = "python analysis/analyse.py "
verify = "python analysis/verify.py "

[dependencies]
premailer = ">=3.10.0,<4"
click = ">=8.3.1,<9"
python-decouple = ">=3.8,<4"
python = "==3.12"

[activation.env]
GAMS_SYSTEM_DIR = "/appl/gams/50.4.1"

[pypi-dependencies]
gamsapi = "==50.4.1"
pybalmorel = ">=1.0.0, <2"
tsam = ">=3.1.2, <4"
ripgrepy = ">=2.2.0, <3"
