PARAMETERS
HYDROGEN_DH2          (YYY,CCCRRRAAA)              'Yearly demand for hydrogen from the transport sector'
HYDROGEN_DH2_VAR_T    (CCCRRRAAA,SSS,TTT)          'Variation profile of H2 demand per region'
HYDROGEN_STOVOL_START (Y,AAA,G,SSS)                'Start level of hydrogen storage'
HYDROGEN_H2TOF        (GGG)             'Factor for need of hydrogen for fuel production'
DAC_DE(GGG)          'Power demand needed to produce biomethane through DAC (Mwe/MWth biomethane)'
DAC_DH(GGG)          'Heat demand needed to produce biomethane through DAC (Mwth/MWth biomethane)'

H2STOVOLTS(Y,AAA,GGG,SSS,TTT)          'Hydrogen storage content to be used in future runs (MWh)'
H2STOVOLTSVAL(Y,AAA,GGG,SSS,TTT)       'Hydrogen storage value to be used in future runs (MWh)'

BIOMETHSTOVOLTS(Y,SSS,TTT)          'Biomethane storage content to be used in future runs (MWh)'
BIOMETHSTOVOLTSVAL(Y,SSS,TTT)       'Biomethane storage value to be used in future runs (MWh)'
;
