POSITIVE VARIABLES
   VHYDROGEN_GH2_T(Y,AAA,GGG,S,T)        'Hydrogen production - existing plants (MWh)'
   VHYDROGEN_STOVOL_T(Y,AAA,G,SSS,T)     'Energy content of hydrogen storage in the beginning of time step T'
   VHYDROGEN_STOLOADT(Y,AAA,GGG,S,T)   'Loading of hydrogen storage'
   VGBIOMETH_T(Y,AAA,GGG,S,T)          'Biomethane producction (MWh)'
   VBIOMETHSTOVOLTS(Y,SSS,T)             'Energy content of biomethane storage in the beginning of time step T'
   VBIOMETH_STOLOADT(Y,S,T)            'Loading of biomethane storage'
   VBIOMETH_STOUNLOADT(Y,S,T)          'Unloading of biomethane storage'

;
