POSITIVE VARIABLES
   VHYDROGEN_GH2_T(Y,AAA,GGG,S,T)        'Hydrogen production - existing plants (MWh)'
   VHYDROGEN_STOVOL_S(Y,AAA,GGG,S)     'Energy content of hydrogen storage in the beginning of time step S'
   VHYDROGEN_STOVOL_T(Y,AAA,G,S,T)     'Energy content of hydrogen storage in the beginning of time step T'
   VHYDROGEN_STOLOADT(Y,AAA,GGG,S,T)   'Loading of hydrogen storage'
   VHYDROGEN_QH2EQ(Y,CCCRRRAAA,S,T,IPLUSMINUS) 'Feasibility in hydrogen balance QH2EQ'
*  VHYDROGEN_DH2F_T(RRR,S,T,DH2F)      'Price flexible hydrogen demand from transport'
;
