Positive variable                VDR_UP(Y,AAA,DR_TECH,S,T) 'Upward regulation of demand response technologies'
Positive variable                VDR_DOWN(Y,AAA,DR_TECH,S,T) 'Downward regulation of demand response technologies'
Positive variable                VDR_SHED_MAXVOL(Y,AAA,DR_TECH,S) 'Accumulated shedding of energy during one week'
Positive variable                VDR_Store_pos(Y,AAA,DR_TECH,S,T) 'storage level - positive'
Positive variable                VDR_Store_neg(Y,AAA,DR_TECH,S,T) 'storage level - negative, energy that needs to be recovered'
;
