* File heattrans_vardeclare.inc for addon heattrans.
* Latest revision 20181014(hr)

POSITIVE VARIABLE  VXH_T(Y,IAAAE,IAAAI,S,T)         "Heat export from area IAAAE towards IAAAI (MW)";
POSITIVE VARIABLE  VXHKN(Y,IAAAE,IAAAI)             "New heat transmission capacity (MW)";
POSITIVE VARIABLE  VXHKNACCUMNET(Y,IAAAE,IAAAI)     "Accumulated new heat transmission investments (MISSING: minus any decommissioning of them due to lifetime expiration) this BB4, at end of previous (i.e., available at start of current) year (MW)";

 