$onmulti
$if     EXIST '../data/INDUSTRY_GGG.inc' $INCLUDE         '../data/INDUSTRY_GGG.inc';
$if not EXIST '../data/INDUSTRY_GGG.inc' $INCLUDE '../../base/data/INDUSTRY_GGG.inc';

$if     EXIST '../data/INDUSTRY_G.inc' $INCLUDE         '../data/INDUSTRY_G.inc';
$if not EXIST '../data/INDUSTRY_G.inc' $INCLUDE '../../base/data/INDUSTRY_G.inc';

$if     EXIST '../data/INDUSTRY_CCCRRRAAA.inc' $INCLUDE         '../data/INDUSTRY_CCCRRRAAA.inc';
$if not EXIST '../data/INDUSTRY_CCCRRRAAA.inc' $INCLUDE '../../base/data/INDUSTRY_CCCRRRAAA.inc';

$if     EXIST '../data/INDUSTRY_AAA.inc' $INCLUDE         '../data/INDUSTRY_AAA.inc';
$if not EXIST '../data/INDUSTRY_AAA.inc' $INCLUDE '../../base/data/INDUSTRY_AAA.inc';

$if     EXIST '../data/INDUSTRY_RRRAAA.inc' $INCLUDE         '../data/INDUSTRY_RRRAAA.inc';
$if not EXIST '../data/INDUSTRY_RRRAAA.inc' $INCLUDE '../../base/data/INDUSTRY_RRRAAA.inc';

$if     EXIST '../data/INDUSTRY_DHUSER.inc' $INCLUDE         '../data/INDUSTRY_DHUSER.inc';
$if not EXIST '../data/INDUSTRY_DHUSER.inc' $INCLUDE '../../base/data/INDUSTRY_DHUSER.inc';


$offmulti
