* PB add-on. Added by Théo Balanza

PARAMETER PB_THRESHOLDS_DATA(YYY,PB_THRESHOLDS_SET) "Planetary Boundaries thresholds downscaled";

PARAMETER PB_LCA_DATA(TECH_GROUP, FFF, PB_GDTYPE_SET, YYY, PB_LCA_DATASET) "LCA data for construction and operation of a generator G in (TECH_GROUP, FFF) for Elec, Heat & CHP";
PARAMETER PB_LCA_DATA_X(IRRRE,IRRRI,YYY,PB_LCA_DATASET) "LCA data for construction of electricity transmission";

PARAMETER PB_LCA_DATA_H2(TECH_GROUP, FFF, PB_GDTYPE_SET, YYY,PB_LCA_DATASET) "LCA data for construction and operation of a generator G in (TECH_GROUP, FFF) for H2";
PARAMETER PB_LCA_DATA_X_H2(IRRRE,IRRRI,YYY,PB_LCA_DATASET) "LCA data for construction of H2 transmission";

PARAMETER PB_LCA_DATA_CCS(TECH_GROUP, FFF, PB_GDTYPE_SET, YYY, PB_LCA_DATASET) "LCA data for construction and operation of a generator G in (TECH_GROUP, FFF) for CCS";



