
$if     EXIST '../data/AGKNDISC_AGKNDISC.inc' $INCLUDE      '../data/AGKNDISC_AGKNDISC.inc';
$if not EXIST '../data/AGKNDISC_AGKNDISC.inc' $INCLUDE '../../base/addons/AGKNdisc/bb4/AGKNDISC_AGKNDISC.inc';

$if     EXIST '../data/AGKNDISC_AGKNDISCSIZESET.inc' $INCLUDE      '../data/AGKNDISC_AGKNDISCSIZESET.inc';
$if not EXIST '../data/AGKNDISC_AGKNDISCSIZESET.inc' $INCLUDE '../../base/addons/AGKNdisc/bb4/AGKNDISC_AGKNDISCSIZESET.inc';

$if     EXIST '../data/AGKNDISC_AGKNDISCDATASET.inc' $INCLUDE      '../data/AGKNDISC_AGKNDISCDATASET.inc';
$if not EXIST '../data/AGKNDISC_AGKNDISCDATASET.inc' $INCLUDE '../../base/addons/AGKNdisc/bb4/AGKNDISC_AGKNDISCDATASET.inc';

