
$if     EXIST '../data/agkndisc_agkndisc.inc' $INCLUDE      '../data/agkndisc_agkndisc.inc';
$if not EXIST '../data/agkndisc_agkndisc.inc' $INCLUDE '../../base/addons/x3v/demodata/agkndisc_agkndisc.inc';

$if     EXIST '../data/agkndisc_agkndiscsizeset.inc' $INCLUDE      '../data/agkndisc_agkndiscsizeset.inc';
$if not EXIST '../data/agkndisc_agkndiscsizeset.inc' $INCLUDE '../../base/addons/x3v/demodata/agkndisc_agkndiscsizeset.inc';

$if     EXIST '../data/agkndisc_agkndiscdataset.inc' $INCLUDE      '../data/agkndisc_agkndiscdataset.inc';
$if not EXIST '../data/agkndisc_agkndiscdataset.inc' $INCLUDE '../../base/addons/agnkdisc/agkndisc_agkndiscdataset.inc';

