Positive variables

VGETOH_CAP1(YYY,AAA,MMM) 'Endogenous max production level for ETOH used to calculate demand charge'
VGETOH_CAP2(YYY,AAA,MMM) 'Endogenous max production level for ETOH used to calculate demand charge'
VGETOH_CAPY(YYY,AAA)     'Endogenous max production level for ETOH used to calculate yearly demand charge'

VDEUSER_CAP1(YYY,RRR,DEUSER,MMM)
VDEUSER_CAP2(YYY,RRR,DEUSER,MMM)
VDEUSER_CAPY(YYY,RRR,DEUSER)
;
