POSITIVE VARIABLES
   VGH2_T(AAA,GGG,S,T)        'Hydrogen production - existing plants (MWh)'
   VGH2N_T(AAA,GGG,S,T)       'Hydrogen production - new plants (MWh)'
   VH2STOVOL_S(AAA,GGG,S)     'Energy content of hydrogen storage in the beginning of time step S'
   VH2STOVOL_T(AAA,G,S,T)     'Energy content of hydrogen storage in the beginning of time step T'
   VH2STOLOADT(AAA,GGG,S,T)   'Loading of hydrogen storage'
   VQH2EQ(RRR,S,T,IPLUSMINUS) 'Feasibility in hydrogen balance QH2EQ'
*  VDH2F_T(RRR,S,T,DH2F)      'Price flexible hydrogen demand from transport'
;
