PARAMETERS
HYDROGEN_DH2          (YYY,CCCRRRAAA)              'Yearly demand for hydrogen from the transport sector'
HYDROGEN_DH2_VAR_T    (CCCRRRAAA,SSS,TTT)          'Variation profile of H2 demand per region'
HYDROGEN_STOVOL_START (Y,AAA,G,SSS)                'Start level of hydrogen storage'
*IDAS new additions
HYDROGEN_H2TOF        (GGG)             'Factor for need of hydrogen for fuel production'
;
