* Fuel transport add-on. Added by Mathias Berg Rosendal

* Variables
$ifi %fueltransport_definition%==region POSITIVE VARIABLE  VFUELTRANSPORT(Y,IRRRE,IRRRI,FFF) 'Transport of fuel F in year Y, from region IRRRE to region IRRRI (GJ)';
$ifi %fueltransport_definition%==area   POSITIVE VARIABLE  VFUELTRANSPORT(Y,IAAAE,IAAAI,FFF) 'Transport of fuel F in year Y, from region IRRRE to region IRRRI (GJ)';

