*Energy sovereignty addon - FF 2025

*Electricity
$ifi %TransInvest%==yes $ifi %SOV_MODE%==group QX_SOV_GRP
$ifi %TransInvest%==yes $ifi %SOV_MODE%==individual QX_SOV_IND

*Hydrogen
$ifi %SOV_H2%==yes $ifi %SOV_MODE%==group QXH2_SOV_GRP
$ifi %SOV_H2%==yes $ifi %SOV_MODE%==individual QXH2_SOV_IND

*OptiFlow (liquid fuels, CO2)
$ifi %SOV_OPTIFLOW%==yes $ifi %SOV_MODE%==group QOPTI_SOV_GRP
$ifi %SOV_OPTIFLOW%==yes $ifi %SOV_MODE%==individual QOPTI_SOV_IND

