* File agkndiscvariables.inc.
* To be used with addon AGKNDISC to the Balmorel model.

*BINARY VARIABLE VGKNDISC(Y,AAA,G,AGKNDISCSIZESET) 'New generation in relation to discrete capacity size investments (binary) (Addon AGKNDISC) (0/1)';
INTEGER VARIABLE VGKNDISC(Y,AAA,G,AGKNDISCSIZESET) 'New generation in relation to discrete capacity size investments (binary) (Addon AGKNDISC) (0/1)';
*VARIABLE VGKNDISC_SPECIAL1(Y,AAA,G,AGKNDISCSIZESET) "Debugging ONLY - see QOBJ in list file";
*VARIABLE VGKNDISC_SPECIAL2(Y,AAA,G,AGKNDISCSIZESET) "Debugging ONLY - see QOBJ in list file";