
* All WW canged to WO

PARAMETER GKFXMR(AAA,GGG)/
* DK_W_AALBORG
DK_W_AALBORG.DK_W_AALBORG_G-HSTORE 3500
DK_W_AALBORG.DK_W_AALBORG_HO-B8-FO 800
DK_W_AALBORG.DK_W_Aalborg_ST-E7-CO 285
DK_W_AALBORG.DK_W_Aalborg_ST-E9-Cosn 372

DK_W_Rural.DK_W_Rural_G-HSTORE   5000
DK_W_Rural.DK_W_Rural_HO-B8-FO   100
DK_W_Rural.DK_W_Rural_ST-B8-CO   54.8000001907349
*DK_W_Rural.DK_W_Rural_ST-B8-NG   44.5
DK_W_Rural.DK_W_Rural_ST-B9-MW   110

*DK_E_Rural.DK_E_Rural_WI 618

* TEST!
DK_W_Rural.DK_W_Urban_ST-E9-Cosn 980

* DK_E_RURAL
DK_E_Rural.DK_E_Rural_ST-B8-CO   37
DK_E_Rural.DK_E_Rural_ST-E7-CO   415
DK_E_Rural.DK_E_Rural_ST-B8-FO   45
DK_E_Rural.DK_E_Rural_HO-B8-FO   30

* Kyndby
DK_E_Rural.DK_E_Rural_ST-C7-FO   550
DK_E_Rural.DK_E_Rural_GT-C8-LO   196

* Asnæs
DK_E_Rural.DK_E_Rural_ST-C8-COs 270
DK_E_Rural.DK_E_Rural_ST-E8-ORs 640
* Stigsnæs
DK_E_Rural.DK_E_Rural_ST-C7-CO 143

*slagelse.'slagelse_ST_C0_CO1'                  143.00
*slagelse.'slagelse_ST_C0_CO2'                  266.00

*soroe.'soroe_ST_E0_CO1'                        640.00
*soroe.'soroe_ST_E0_CO2'                        270.00
* Ikke i drift. Ingen produktion i 2004
*      *soroe.'soroe_ST_E0_CO3'                        270.00
*soroe.'soroe_ST_E0_CO4'                        147.00

* ---- DK_E_Urban
DK_E_Urban.DK_E_Rural_ST-E8-ST   70

*DK_E_Urban.DK_E_Urban_CC-B8-NG  155
*DK_E_Urban.DK_E_Urban_CC-B8-NG  0

DK_E_Urban.DK_E_Urban_G-HSTORE=10000
DK_E_Urban.DK_E_Urban_HO-B8-FO=1500

*DK_E_Urban.DK_E_Urban_ST-B8-NG=229
*DK_E_Urban.DK_E_Urban_ST-B8-NG   154

DK_E_Urban.DK_E_Urban_ST-B9-ST=35
DK_E_Urban.DK_E_Urban_ST-E0-NGsn=267.5
DK_E_Urban.DK_E_Urban_ST-E0-Wosn=267.5
DK_E_Urban.DK_E_Urban_ST-E9-Cosn=500

* Amager værket er omfattet af DK_E_Urban
*amagerf.'amagerf_HO_LO'                     102.00
*amagerf.'amagerf_ST_B0_MW'                     28.50
* Lukket:
** amagerf.'amagerf_ST_E0_CO1'                    136.00
*amagerf.'amagerf_ST_E0_CO3'                    250.00
*amagerf.'amagerf_ST_E0_ST2'                    91.00

billesboelle.'billesboelle_GE_B0_NG'           1.11
billesboelle.'billesboelle_HO_NG'           3.50
brande.'brande_GE_B0_NG'                       6.27
brande.'brande_HO_LO'                       1.00
brande.'brande_HO_NG'                       5.70
brande.'brande_HO_WO'                       1.20
brande.'brande_HYRR_HY'                        0.25
* Nogle af disse er måske på Avedøre... men det er tvivlsomt
broendby.'broendby_GE_B0_NG'                   6.20
broendby.'broendby_GE_C0_LO'                  1.68
broendby.'broendby_HO_FO'                   90.00
broendby.'broendby_HO_LO'                   227.60
broendby.'broendby_HO_NG'                   111.80
broendby.'broendby_SOLE_SOL'                   0.01
* Avedoere er omfattet af DK_E_Urban
* avedoere.'broendby_ST_E0_CO1'                  250.00
* Avedøre blok 2 længere nede.
* avedoere.DK_E_Urban_ST-E0-NGsn                 380
* avedoere.DK_E_Urban_ST-E0-WOsn                 190
dragoer.'dragoer_GE_B0_NG'                     1.44
dragoer.'dragoer_GE_C0_NG'                     0.20
dragoer.'dragoer_HO_LO'                     45.00
dragoer.'dragoer_SOLE_SOL'                     0.02
egtved.'egtved_CC_B0_MW'                       33.00
egtved.'egtved_GE_B0_NG'                       46.42
egtved.'egtved_GE_C0_NG'                       0.40
egtved.'egtved_HO_LO'                       37.05
egtved.'egtved_HO_NG'                       342.36
egtved.'egtved_HO_WO'                       12.30
egtved.'egtved_HYRR_HY'                        1.19
ellidshoej.'ellidshoej_GE_B0_NG'               19.25
ellidshoej.'ellidshoej_GT_B0_NG'               5.20
ellidshoej.'ellidshoej_HO_LO'               28.30
ellidshoej.'ellidshoej_HO_NG'               34.25
ellidshoej.'ellidshoej_HO_ST'               1.60
froeslev.'froeslev_CC_B0_NG'                  58.00
froeslev.'froeslev_GE_B0_NG'                   23.42
*froeslev.'froeslev_HO_CO4'                  0.00
*froeslev.'froeslev_HO_CO5'                  0.00
froeslev.'froeslev_HO_FO'                   115.20
froeslev.'froeslev_HO_LO'                   26.00
froeslev.'froeslev_HO_NG'                   153.97
froeslev.'froeslev_HO_ST'                   3.15
froeslev.'froeslev_HO_WO'                   1.75
froeslev.'froeslev_HYRR_HY'                    7.0e-03
* Findes i DK_W_Rural
* Ikke i drift:
** froeslev.'froeslev_ST_C0_CO3'                  327.00
*froeslev.'froeslev_ST_E0_CO2'                  626.00
haverslev.'haverslev_GE_B0_NG'                 41.25
haverslev.'haverslev_GT_B0_NG'                 0.92
haverslev.'haverslev_HO_FO'                 19.00
haverslev.'haverslev_HO_LO'                 40.00
haverslev.'haverslev_HO_MW'                 24.10
haverslev.'haverslev_HO_NG'                 72.60
haverslev.'haverslev_HO_ST'                 11.15
haverslev.'haverslev_HO_WO'                 38.60
haverslev.'haverslev_ST_B0_MW'                 2.89
herning.'herning_CC_B0_NG'                     107.00
herning.'herning_GE_B0_LO'                     0.94
herning.'herning_GE_B0_NG'                     92.65
herning.'herning_GE_B0_WO'                     0.05
* Del af DK_W_Rural
*herning.'herning_GE_C0_LO1'                    0.21
*herning.'herning_GE_C0_LO2'                    0.33
*herning.'herning_GE_C0_LO3'                    0.27
*herning.'herning_GE_C0_LO4'                    0.38
herning.'herning_GT_B0_NG'                     24.30
*herning.'herning_GT_C0_LO5'                    12.00
*herning.'herning_HO_CO6'                    0.00
herning.'herning_HO_FO'                     221.85
*herning.'herning_HO_LO'                     842.20
*herning.'herning_HO_LO2'                    69.60
herning.'herning_HO_MW'                     46.10
herning.'herning_HO_NG'                     436.00
* No information:
* herning.'herning_HO_NG2'                    0.00
herning.'herning_HO_ST'                     74.00
herning.'herning_HO_WO'                     144.64
herning.'herning_HYRR_HY'                      0.51
*herning.'herning_ST_B0_CO'                     19.60
*herning.'herning_ST_B0_FO'                     5.00
*herning.'herning_ST_B0_MW'                     27.15
herning.'herning_ST_B0_WO'                     5.00
*herning.'herning_ST_E0_CO1'                    48.30
* Findes i DK_W_AAHURS:
*herning.'herning_ST_E0_CO3'                    350.00
*herning.'herning_ST_E0_CO4'                    350.00
*herning.'herning_ST_E0_WO1'                    89.00
* DK_W_AARHUS
DK_W_AARHUS.DK_W_AARHUS_G-HSTORE         3500
DK_W_AARHUS.DK_W_AARHUS_HO-B8-FO         600
DK_W_AARHUS.DK_W_Aarhus_ST-B9-MW         60
DK_W_AARHUS.DK_W_Aarhus_ST-E8-Cos        665
DK_W_AARHUS.DK_W_Aarhus_ST-E8-ST         35



hoejby.'hoejby_GE_B0_NG'                       58.15
hoejby.'hoejby_GT_B0_NG'                       7.10
hoejby.'hoejby_HO_FO'                       159.90
hoejby.'hoejby_HO_LO'                       223.59
hoejby.'hoejby_HO_NG'                       134.05
hoejby.'hoejby_HO_ST'                       3.78
hoejby.'hoejby_HO_WO'                       187.51
hoejby.'hoejby_HYRR_HY'                        6.0e-03
hoejby.'hoejby_ST_B0_MW'                       4.50
* Fjernet da de eksisterer i DK_W_ODENSE:
*hoejby.'hoejby_ST_B0_MW1'                      24.00
*hoejby.'hoejby_ST_E0_NG3'                      269.00
*hoejby.'hoejby_ST_E0_CO2'                      407.00
* DK_W_ODENSE
DK_W_ODENSE.DK_W_ODENSE_G-HSTORE         3500
DK_W_ODENSE.DK_W_ODENSE_HO-B8-FO         600
DK_W_ODENSE.DK_W_Odense_ST-B9-MW         24
DK_W_ODENSE.DK_W_Odense_ST-E7-NG         217
DK_W_ODENSE.DK_W_Odense_ST-E9-Cosn       339
karlslunde.'karlslunde_GE_B0_NG'               4.22
karlslunde.'karlslunde_HO_LO'               75.50
karlslunde.'karlslunde_HO_NG'               11.00
karup.'karup_GE_B0_NG'                         30.23
karup.'karup_HO_LO'                         0.87
karup.'karup_HO_NG'                         120.42
karup.'karup_HO_WO'                         10.00
karup.'karup_HYRR_HY'                          3.92
koege.'koege_GE_B0_NG'                         14.05
koege.'koege_HO_FO'                         10.00
koege.'koege_HO_LO'                         12.00
koege.'koege_HO_NG'                         6.14
koege.'koege_HO_ST'                         4.00
koege.'koege_ST_B0_NG'                         5.80
koege.'koege_ST_B0_WO'                         26.00
koelbjerg.'koelbjerg_GE_B0_NG'                 59.00
koelbjerg.'koelbjerg_HO_CO'                 10.00
koelbjerg.'koelbjerg_HO_FO'                 3.60
koelbjerg.'koelbjerg_HO_LO'                 62.47
koelbjerg.'koelbjerg_HO_NG'                 77.85
koelbjerg.'koelbjerg_HO_WO'                 24.90
koelbjerg.'koelbjerg_HYRR_HY'                  0.11
koelbjerg.'koelbjerg_ST_B0_CO'                 5.30
koelbjerg.'koelbjerg_ST_B0_FO'                 4.00
koelbjerg.'koelbjerg_ST_B0_NG'                 11.00
koelbjerg.'koelbjerg_ST_B0_WO'                 4.68
liselskaer.'liselskaer_CC_B0_MW'               5.40
liselskaer.'liselskaer_GE_B0_NG'               40.26
liselskaer.'liselskaer_HO_NG'               107.32
liselskaer.'liselskaer_HYRR_HY'                0.40
liselskaer.'liselskaer_ST_B0_NG'               3.20
litorup.'litorup_GE_B0_NG'                     8.59
litorup.'litorup_HO_LO'                     7.00
litorup.'litorup_HO_NG'                     12.90
lynge.'lynge_CC_B0_NG'                        77.00
lynge.'lynge_GE_B0_NG'                         33.69
lynge.'lynge_GE_B0_WO'                         0.09
lynge.'lynge_GT_B0_NG'                         94.10
lynge.'lynge_HO_FO'                         3.15
lynge.'lynge_HO_MW'                         21.00
lynge.'lynge_HO_NG'                         221.38
lynge.'lynge_HO_WO'                         15.00
lynge.'lynge_HYRR_HY'                          0.02
lynge.'lynge_ST_B0_MW'                         7.40
middelfart.'middelfart_GE_B0_NG'               6.18
middelfart.'middelfart_HO_LO'               19.30
middelfart.'middelfart_HO_MW'               7.00
middelfart.'middelfart_HO_NG'               16.34
middelfart.'middelfart_HYRR_HY'                0.01
maaloev.'maaloev_GE_B0_NG'                     51.88
*maaloev.'maaloev_GE_C0_LO4'                    20.00
maaloev.'maaloev_GT_B0_NG'                     4.50
*maaloev.'maaloev_GT_C0_LO6'                    63.00
*maaloev.'maaloev_GT_C0_NG5'                    63.00
*maaloev.'maaloev_GT_C0_NG7'                    2.00
*maaloev.'maaloev_HO_FO8'                    50.00
*maaloev.'maaloev_HO_FO9'                    0.00
maaloev.'maaloev_HO_LO'                     30.40
maaloev.'maaloev_HO_MW'                     16.00
maaloev.'maaloev_HO_NG'                     68.50
maaloev.'maaloev_HO_WO'                     40.70
*maaloev.'maaloev_ST_C0_FO2'                    260.00
*maaloev.'maaloev_ST_C0_FO3'                    260.00
noerskov.'noerskov_GE_B0_NG'                   42.85
noerskov.'noerskov_GT_B0_NG'                   0.80
noerskov.'noerskov_HO_FO'                   9.90
noerskov.'noerskov_HO_LO'                   7.50
noerskov.'noerskov_HO_NG'                   59.20
noerskov.'noerskov_HO_WO'                   25.28
noerskov.'noerskov_ST_B0_CO'                   6.70
nyborg.'nyborg_CC_B0_MW'                       21.00
nyborg.'nyborg_GE_B0_NG'                       0.04
*nyborg.'nyborg_GT_B0_NG'                       4.90
nyborg.'nyborg_HO_NG'                       12.04
nyborg.'nyborg_HO_WO'                       71.90
nyborg.'nyborg_HYRR_HY'                        0.04
nybro.'nybro_GE_B0_NG'                         7.87
nybro.'nybro_GT_B0_NG'                         4.00
nybro.'nybro_HO_LO'                         4.65
nybro.'nybro_HO_NG'                         9.16
nybro.'nybro_HO_WO'                         1.90
nybro.'nybro_HYRR_HY'                          0.02
DK_E_Rural.'OEST_GE_B0_LO'                     0.35
DK_E_Rural.'OEST_GE_B0_NG'                     1.24
*DK_E_Rural.'OEST_GE_C0_LO2'                    19.60
DK_E_Rural.'OEST_HO_CO'                     26.00
DK_E_Rural.'OEST_HO_FO'                     54.40
DK_E_Rural.'OEST_HO_LO'                     108.30
DK_E_Rural.'OEST_HO_MW'                     22.00
DK_E_Rural.'OEST_HO_ST'                     87.65
DK_E_Rural.'OEST_HO_WO'                     129.00
*DK_E_Rural.'OEST_ST_B0_CO4'                    37.00
*DK_E_Rural.'OEST_ST_B0_FO'                     34.00
*DK_E_Rural.'OEST_ST_B0_FO1'                    4.00
DK_E_Rural.'OEST_ST_B0_MW'                     6.70
DK_E_Rural.'OEST_ST_B0_ST'                     11.30
*DK_E_Rural.'OEST_ST_C0_FO3'                    27.50
pottehuse.'pottehuse_GE_B0_NG'                 3.17
pottehuse.'pottehuse_HO_LO'                 43.30
pottehuse.'pottehuse_HO_MW'                 12.40
pottehuse.'pottehuse_HO_NG'                 230.10
pottehuse.'pottehuse_HO_WO'                 8.20
pottehuse.'pottehuse_HYRR_HY'                  0.95
pottehuse.'pottehuse_SOLE_SOL'                 0.10
pottehuse.'pottehuse_ST_B0_MW'                 6.26
ringsted.'ringsted_CC_B0_MW'                   38.00
ringsted.'ringsted_GE_B0_NG'                   63.86
ringsted.'ringsted_GT_C0_LO2'                  70.00
ringsted.'ringsted_HO_MW'                   10.00
ringsted.'ringsted_HO_NG'                   232.66
ringsted.'ringsted_HO_ST'                   8.00
ringsted.'ringsted_ST_B0_ST'                   5.00
ringsted.'ringsted_ST_B0_ST3'                  9.00
slagelse.'slagelse_GE_B0_NG'                   13.41
slagelse.'slagelse_GE_C0_NG'                   0.31
slagelse.'slagelse_GT_B0_NG'                   0.97
*slagelse.'slagelse_HO_FO3'                  2.00
slagelse.'slagelse_HO_NG'                   139.80
slagelse.'slagelse_HO_ST'                   4.50
slagelse.'slagelse_HO_WO'                   7.80
slagelse.'slagelse_ST_B0_MW'                   12.00
* Sigsnæsværket fjernet fordi det er omfattet af DK_E_Rural
*slagelse.'slagelse_ST_C0_CO1'                  143.00
*slagelse.'slagelse_ST_C0_CO2'                  266.00
soroe.'soroe_GE_B0_NG'                         31.83
soroe.'soroe_HO_FO'                         16.70
*soroe.'soroe_HO_FO6'                        42.00
soroe.'soroe_HO_LO'                         19.40
soroe.'soroe_HO_NG'                         62.00
soroe.'soroe_HO_ST'                         11.50
soroe.'soroe_HO_WO'                         11.10
* Asnæsværket fjernet fordi det er omfattet af DK_E_Rural
*soroe.'soroe_ST_E0_CO1'                        640.00
*soroe.'soroe_ST_E0_CO2'                        270.00
* Ikke i drift. Ingen produktion i 2004
*           soroe.'soroe_ST_E0_CO3'                        270.00
*soroe.'soroe_ST_E0_CO4'                        147.00
standst.'standst_GE_B0_NG'                     33.98
*standst.'standst_GT_B0_NG'                     0.60
standst.'standst_HO_LO'                     11.43
standst.'standst_HO_NG'                     94.50
standst.'standst_HO_WO'                     32.26
standst.'standst_HYRR_HY'                      0.10
standst.'standst_ST_B0_MW'                     2.60
stenlille.'stenlille_HO_LO'                 3.30
stenlille.'stenlille_HO_ST'                 2.50
DK_E_Urban.'sydhavnen_CC_B0_NG'                 13.30
*Avedoere.'sydhavnen_CC_E0_NG1'                591.00
* Effekt fordelt på naturgas og træ i forholdet 2-1
*Avedoere.'sydhavnen_CC_E0_NG1'                380.00
DK_E_Urban.'sydhavnen_GE_B0_NG'                 0.55
* Ses på museet Dieselhouse
*HCOersted.'sydhavnen_GE_C0_LO3'                12.00
* Svanemølle blok 7:
*HCOersted.'sydhavnen_GT_B0_NG2'                60.00
*HCO Blok 8:
*HCOersted.'sydhavnen_GT_B0_NG4'                24.30
DK_E_Urban.'sydhavnen_HO_FO'                 171.00
DK_E_Urban.'sydhavnen_HO_LO'                 331.90
DK_E_Urban.'sydhavnen_HO_NG'                 47.80
DK_E_Urban.'sydhavnen_SOLE_SOL'                 0.04
* Svanemøllen blok 1 + HCØ blok 1-4 med 70 MW Skrottet i 2005:
*HCOersted.'sydhavnen_ST_E0_NG1'                155
* HCØ Blok 7:
*HCOersted.'sydhavnen_ST_E0_NG2'                88.00
skaerbaek.'taulov_CC_B0_NG'                       6.25
skaerbaek.'taulov_GE_B0_NG'                       1.17
skaerbaek.'taulov_GT_B0_NG'                       33.40
skaerbaek.'taulov_HO_LO'                       139.41
skaerbaek.'taulov_HO_NG'                       42.00
skaerbaek.'taulov_HO_NG4'                      0.00
*Seperat område til Skærbæk værketet
* Mangler i systemplan 2006. Er skrottet.
** skaerbaek.'taulov_ST_E0_NG1'                      93.00
*skaerbaek.'taulov_ST_E0_NG3'                      392.00
DK_W_TREFOR.DK_W_TREFOR_G-HSTORE=3500
DK_W_TREFOR.DK_W_TREFOR_HO-B8-FO=800
DK_W_TREFOR.DK_W_Trefor_ST-E9-NGn=391
terkelsboel.'terkelsboel_CC_B0_NG'             6.00
terkelsboel.'terkelsboel_GE_B0_NG'             14.60
terkelsboel.'terkelsboel_GT_B0_NG'             14.30
terkelsboel.'terkelsboel_HO_LO'             28.45
terkelsboel.'terkelsboel_HO_NG'             107.81
terkelsboel.'terkelsboel_HO_WO'             5.80
terkelsboel.'terkelsboel_HYRR_HY'              0.03
terkelsboel.'terkelsboel_ST_B0_WO'             0.60
torslunde.'torslunde_GE_B0_NG'                 3.33
torslunde.'torslunde_HO_LO'                 77.70
torslunde.'torslunde_HO_MW'                 28.00
torslunde.'torslunde_HO_NG'                 101.90
torslunde.'torslunde_ST_B0_MW'                 13.70
ullerslev.'ullerslev_GE_B0_NG'                 13.39
ullerslev.'ullerslev_HO_LO'                 66.82
ullerslev.'ullerslev_HO_NG'                 19.60
ullerslev.'ullerslev_HYRR_HY'                  0.02
vallensbaek.'vallensbaek_GE_B0_NG'             4.32
vallensbaek.'vallensbaek_HO_LO'             38.99
vallensbaek.'vallensbaek_HO_MW'             104.00
vallensbaek.'vallensbaek_HO_NG'             42.50
vallensbaek.'vallensbaek_HO_WO'             32.00
vallensbaek.'vallensbaek_ST_B0_MW'             39.00
varde.'varde_GE_B0_NG'                         16.83
varde.'varde_GT_B0_NG'                         3.74
varde.'varde_HO_FO'                         7.00
varde.'varde_HO_LO'                         202.46
varde.'varde_HO_NG'                         67.54
varde.'varde_HO_WO'                         51.45
varde.'varde_HYRR_HY'                          1.60
*varde.'varde_ST_B0_MW'                         18.00
*varde.'varde_ST_E0_CO1'                        378.00
DK_W_Rural.'VEST_GE_B0_NG'                     0.45
DK_W_Rural.'VEST_HO_FO'                     24.60
DK_W_Rural.'VEST_HO_LO'                     5.10
DK_W_Rural.'VEST_HO_ST'                     22.05
DK_W_Rural.'VEST_HO_WO'                     25.53
DK_W_Rural.'VEST_ST_B0_ST'                     2.30
viborg.'viborg_CC_B0_NG'                       87.00
viborg.'viborg_CC_B0_WO'                       1.40
viborg.'viborg_GE_B0_NG'                       90.15
viborg.'viborg_GT_B0_NG'                       20.10
viborg.'viborg_HO_FO'                       97.45
viborg.'viborg_HO_LO'                       60.90
viborg.'viborg_HO_NG'                       445.13
viborg.'viborg_HO_ST'                       8.80
viborg.'viborg_HO_WO'                       157.13
viborg.'viborg_HYRR_HY'                        0.02
viborg.'viborg_ST_B0_MW'                       32.92
aalborg.'aalborg_CC_B0_NG'                     56.15
aalborg.'aalborg_GE_B0_NG'                     145.28
aalborg.'aalborg_GE_C0_NG'                     0.05
aalborg.'aalborg_GT_B0_NG'                     39.96
aalborg.'aalborg_GT_C0_LO3'                    25.00
aalborg.'aalborg_HO_CO5'                    0.00
aalborg.'aalborg_HO_LO'                     260.15
aalborg.'aalborg_HO_MW'                     48.60
aalborg.'aalborg_HO_NG'                     582.13
aalborg.'aalborg_HO_ST'                     5.00
aalborg.'aalborg_HO_WO'                     65.86
aalborg.'aalborg_HYRR_HY'                      0.21
aalborg.'aalborg_ST_B0_MW'                     14.10
aalborg.'aalborg_ST_B0_NG'                     0.73
*Findes i DK_W_AALBORG
*aalborg.'aalborg_ST_E0_CO2'                    285.00
*aalborg.'aalborg_ST_E0_CO4'                    380.00
/;

GKFX(YYY,AAA,GGG)$(ICA('Denmark',AAA) and GDATA(GGG,'GDTYPE')<> 10)=0;
GKFX(YYY,MRAREAS,GGG)$(GDATA(GGG,'GDTYPE')<> 10)=GKFXMR(MRAREAS,GGG);

GKFX(YYY,MRAREAS(AAA),'DK_E_1_G-HSTORE')$(not SUM(IGHSTO, GKFX('2006',AAA,IGHSTO)))
=8*(SUM(IGKHNOSTO, GKFX(YYY,AAA,IGKHNOSTO)) + SUM(G$(IGKE(G) and not IGH(G) and GDATA(G,'GDCB')and GKFX(YYY,AAA,G)>0), GKFX(YYY,AAA,G)/GDATA(G,'GDCB')));



SETS MR2CENTRAL(AAA,AAA,GGG)
/
Hoejby.DK_W_Odense.DK_W_Odense_ST-E7-NG
Avedoere.DK_E_Urban.DK_E_Urban_ST-E0-NGsn
HCOersted.DK_E_Urban.DK_E_Urban_ST-B8-NG
HCOersted.DK_E_Urban.'sydhavnen_CC_B0_NG'
HCOersted.DK_E_Urban.'sydhavnen_HO_NG'
HCOersted.DK_E_Urban.'sydhavnen_GE_B0_NG'
SKAERBAEK.DK_W_TREFOR.DK_W_Trefor_ST-E9-NGn
/;