* Ancilliary services by Juan Gea Bermúdez 2019.

* Variables
POSITIVE VARIABLE VASFCRUP(Y,AAA,G,S,T) "Ancilliary service: technology allowed to provide for frequency containment reserves for up regulation (MW)";
POSITIVE VARIABLE VASAFRRUP(Y,AAA,G,S,T) "Ancilliary service: technology allowed to provide for automatic frequency restoration reserves for up regulation (MW)";
POSITIVE VARIABLE VASMFRRUP(Y,AAA,G,S,T) "Ancilliary service: technology allowed to provide for manual frequency restoration reserves for up regulation (MW)";
POSITIVE VARIABLE VASMRRUP(Y,AAA,G,S,T) "Ancilliary service: technology allowed to provide for manual replacement reserves for up regulation (MW)";

POSITIVE VARIABLE VASFCRDOWN(Y,AAA,G,S,T) "Ancilliary service: technology allowed to provide for frequency containment reserves for down regulation (MW)";
POSITIVE VARIABLE VASAFRRDOWN(Y,AAA,G,S,T) "Ancilliary service: technology allowed to provide for automatic frequency restoration reserves for down regulation (MW)";
POSITIVE VARIABLE VASMFRRDOWN(Y,AAA,G,S,T) "Ancilliary service: technology allowed to provide for manual frequency restoration reserves for down regulation (MW)";
POSITIVE VARIABLE VASMRRDOWN(Y,AAA,G,S,T) "Ancilliary service: technology allowed to provide for manual replacement reserves for down regulation (MW)";
