PARAMETERS
STEPWISEPRICE_GMIDF(YYY,CCC,STEPWISEPRICE_FFF)   'Amount of fuel for which the fuel price from FUELPRICE.INC holds (GJ) (only used for setting amounts)'
STEPWISEPRICE_AMOUNT(YYY,CCC,STEPWISEPRICE_L,STEPWISEPRICE_FFF)           'Amount that can be bought in each line segment GJ'
STEPWISEPRICE_FUELPRICE_STEP(YYY,CCC,STEPWISEPRICE_L,STEPWISEPRICE_FFF) 'Fuel price in each line segment for each fuel (OMONEY/GJ)'
;
