PARAMETER TECHGROUPKPOT_STEP(CCCRRRAAA,TECH_GROUP,KPOTSTEP) 'share of TECHGROUPKPOT belonging to each step (fraction)';
PARAMETER KPOTSTEP_FLH(CCCRRRAAA,TECH_GROUP,KPOTSTEP) 'multiplier to FLH (1 equals no change)';
PARAMETER GKACCUMNET_KPOTSTEP(YYY,AAA,GGG,KPOTSTEP) "Resulting technology capacity development for technologies with stepwise capacity potentials at end of (ULTimo) previous (i.e., start of current) year (MW) (MWh for storage) to be transferred to future runs";

