* File HYRSBB123internals.inc for the Balmorel model.
* For use with addon HYRSBB123.
* Latest revision 20170419 (hr) 

$ifi not %BB4%==yes POSITIVE VARIABLE VIHYRSBB12DELTAMHW(AAA,IHYRSBB12DELTASET)   "Amount of additional hydro energy allocated this season during optimization of model Balbase3 (MWh)";

$ifi     %BB4%==yes POSITIVE VARIABLE VIHYRSBB12DELTAMHW(Y,AAA,IHYRSBB12DELTASET) "Amount of additional hydro energy allocated this season during optimization of model Balbase3 (MWh)";
