
SET PROCTECHTYPE(IPROCFROM,TECHTYPE)
/


*BiogasProd_single                  .  Biogas
BiogasProd_mix                     .  Biogas
Biogas_Grid_OUT                    .  Biogas

BiogasUpgr_BMETH_20                .  BiogasUpgr
BiogasUpgr_BMETH_25                .  BiogasUpgr
BiogasUpgr_BMETH_30                .  BiogasUpgr
BiogasUpgr_BMETH_35                .  BiogasUpgr
BiogasUpgr_BMETH_40                .  BiogasUpgr
BiogasUpgr_BMETH_45                .  BiogasUpgr
BiogasUpgr_BMETH_50                .  BiogasUpgr


********gasification
TG_MW_20                           .  Gasifier
TG_MW_25                           .  Gasifier
TG_MW_30                           .  Gasifier
TG_MW_35                           .  Gasifier
TG_MW_40                           .  Gasifier
TG_MW_45                           .  Gasifier
TG_MW_50                           .  Gasifier

TG_ST_20                           .  Gasifier
TG_ST_25                           .  Gasifier
TG_ST_30                           .  Gasifier
TG_ST_35                           .  Gasifier
TG_ST_40                           .  Gasifier
TG_ST_45                           .  Gasifier
TG_ST_50                           .  Gasifier

TG_WO_20                           .  Gasifier
TG_WO_25                           .  Gasifier
TG_WO_30                           .  Gasifier
TG_WO_35                           .  Gasifier
TG_WO_40                           .  Gasifier
TG_WO_45                           .  Gasifier
TG_WO_50                           .  Gasifier

TG_WP_20                           .  Gasifier
TG_WP_25                           .  Gasifier
TG_WP_30                           .  Gasifier
TG_WP_35                           .  Gasifier
TG_WP_40                           .  Gasifier
TG_WP_45                           .  Gasifier
TG_WP_50                           .  Gasifier


BIO_TG_GRID_IN                     .  Gasifier

ThermGasific_SNG_MW_20             .  SNG
ThermGasific_SNG_MW_25             .  SNG
ThermGasific_SNG_MW_30             .  SNG
ThermGasific_SNG_MW_35             .  SNG
ThermGasific_SNG_MW_40             .  SNG
ThermGasific_SNG_MW_45             .  SNG
ThermGasific_SNG_MW_50             .  SNG

ThermGasific_SNG_ST_20             .  SNG
ThermGasific_SNG_ST_25             .  SNG
ThermGasific_SNG_ST_30             .  SNG
ThermGasific_SNG_ST_35             .  SNG
ThermGasific_SNG_ST_40             .  SNG
ThermGasific_SNG_ST_45             .  SNG
ThermGasific_SNG_ST_50             .  SNG

ThermGasific_SNG_WO_20             .  SNG
ThermGasific_SNG_WO_25             .  SNG
ThermGasific_SNG_WO_30             .  SNG
ThermGasific_SNG_WO_35             .  SNG
ThermGasific_SNG_WO_40             .  SNG
ThermGasific_SNG_WO_45             .  SNG
ThermGasific_SNG_WO_50             .  SNG

ThermGasific_SNG_WP_20             .  SNG
ThermGasific_SNG_WP_25             .  SNG
ThermGasific_SNG_WP_30             .  SNG
ThermGasific_SNG_WP_35             .  SNG
ThermGasific_SNG_WP_40             .  SNG
ThermGasific_SNG_WP_45             .  SNG
ThermGasific_SNG_WP_50             .  SNG

BIO_SNG_OUT                        .  SNG

ThermGasific_SYNGAS_MW_20          .  SYNGAS
ThermGasific_SYNGAS_MW_25          .  SYNGAS
ThermGasific_SYNGAS_MW_30          .  SYNGAS
ThermGasific_SYNGAS_MW_35          .  SYNGAS
ThermGasific_SYNGAS_MW_40          .  SYNGAS
ThermGasific_SYNGAS_MW_45          .  SYNGAS
ThermGasific_SYNGAS_MW_50          .  SYNGAS

ThermGasific_SYNGAS_ST_20          .  SYNGAS
ThermGasific_SYNGAS_ST_25          .  SYNGAS
ThermGasific_SYNGAS_ST_30          .  SYNGAS
ThermGasific_SYNGAS_ST_35          .  SYNGAS
ThermGasific_SYNGAS_ST_40          .  SYNGAS
ThermGasific_SYNGAS_ST_45          .  SYNGAS
ThermGasific_SYNGAS_ST_50          .  SYNGAS

ThermGasific_SYNGAS_WO_20          .  SYNGAS
ThermGasific_SYNGAS_WO_25          .  SYNGAS
ThermGasific_SYNGAS_WO_30          .  SYNGAS
ThermGasific_SYNGAS_WO_35          .  SYNGAS
ThermGasific_SYNGAS_WO_40          .  SYNGAS
ThermGasific_SYNGAS_WO_45          .  SYNGAS
ThermGasific_SYNGAS_WO_50          .  SYNGAS

ThermGasific_SYNGAS_WP_20          .  SYNGAS
ThermGasific_SYNGAS_WP_25          .  SYNGAS
ThermGasific_SYNGAS_WP_30          .  SYNGAS
ThermGasific_SYNGAS_WP_35          .  SYNGAS
ThermGasific_SYNGAS_WP_40          .  SYNGAS
ThermGasific_SYNGAS_WP_45          .  SYNGAS
ThermGasific_SYNGAS_WP_50          .  SYNGAS

BIO_SYNGAS_GRID_OUT                .  SYNGAS

****hydrogen production
SOEC_20                            .  Hydrogen
SOEC_25                            .  Hydrogen
SOEC_30                            .  Hydrogen
SOEC_35                            .  Hydrogen
SOEC_40                            .  Hydrogen
SOEC_45                            .  Hydrogen
SOEC_50                            .  Hydrogen


*********meth
Methanisation_Bio_BioGas_20           .  Methanation_Biogas
Methanisation_Bio_BioGas_25           .  Methanation_Biogas
Methanisation_Bio_BioGas_30           .  Methanation_Biogas
Methanisation_Bio_BioGas_35           .  Methanation_Biogas
Methanisation_Bio_BioGas_40           .  Methanation_Biogas
Methanisation_Bio_BioGas_45           .  Methanation_Biogas
Methanisation_Bio_BioGas_50           .  Methanation_Biogas


Methane_synthesis_TG_20           .  Methane_synthesis
Methane_synthesis_TG_25           .  Methane_synthesis
Methane_synthesis_TG_30           .  Methane_synthesis
Methane_synthesis_TG_35           .  Methane_synthesis
Methane_synthesis_TG_40           .  Methane_synthesis
Methane_synthesis_TG_45           .  Methane_synthesis
Methane_synthesis_TG_50           .  Methane_synthesis



Methanol_synthesis_TG_20           .  Methanol_synthesis
Methanol_synthesis_TG_25           .  Methanol_synthesis
Methanol_synthesis_TG_30           .  Methanol_synthesis
Methanol_synthesis_TG_35           .  Methanol_synthesis
Methanol_synthesis_TG_40           .  Methanol_synthesis
Methanol_synthesis_TG_45           .  Methanol_synthesis
Methanol_synthesis_TG_50           .  Methanol_synthesis


*****BIOJET*****
BioJet_ST_20                       .  BioJet
BioJet_ST_25                       .  BioJet
BioJet_ST_30                       .  BioJet
BioJet_ST_35                       .  BioJet
BioJet_ST_40                       .  BioJet
BioJet_ST_45                       .  BioJet
BioJet_ST_50                       .  BioJet

BioJet_WO_20                       .  BioJet
BioJet_WO_25                       .  BioJet
BioJet_WO_30                       .  BioJet
BioJet_WO_35                       .  BioJet
BioJet_WO_40                       .  BioJet
BioJet_WO_45                       .  BioJet
BioJet_WO_50                       .  BioJet

BioJet_WP_20                       .  BioJet
BioJet_WP_25                       .  BioJet
BioJet_WP_30                       .  BioJet
BioJet_WP_35                       .  BioJet
BioJet_WP_40                       .  BioJet
BioJet_WP_45                       .  BioJet
BioJet_WP_50                       .  BioJet


BioJet_ST_H2_20                    .  BioJet
BioJet_ST_H2_25                    .  BioJet
BioJet_ST_H2_30                    .  BioJet
BioJet_ST_H2_35                    .  BioJet
BioJet_ST_H2_40                    .  BioJet
BioJet_ST_H2_45                    .  BioJet
BioJet_ST_H2_50                    .  BioJet

BioJet_WO_H2_20                    .  BioJet
BioJet_WO_H2_25                    .  BioJet
BioJet_WO_H2_30                    .  BioJet
BioJet_WO_H2_35                    .  BioJet
BioJet_WO_H2_40                    .  BioJet
BioJet_WO_H2_45                    .  BioJet
BioJet_WO_H2_50                    .  BioJet

BioJet_WP_H2_20                    .  BioJet
BioJet_WP_H2_25                    .  BioJet
BioJet_WP_H2_30                    .  BioJet
BioJet_WP_H2_35                    .  BioJet
BioJet_WP_H2_40                    .  BioJet
BioJet_WP_H2_45                    .  BioJet
BioJet_WP_H2_50                    .  BioJet


BioJet_SUM                         .  BioJet
**************

Ethanol_20                         .  Ethanol
Ethanol_25                         .  Ethanol
Ethanol_30                         .  Ethanol
Ethanol_35                         .  Ethanol
Ethanol_40                         .  Ethanol
Ethanol_45                         .  Ethanol
Ethanol_50                         .  Ethanol


*TG_FT_Biodiesel_MW_20              .  Biodiesel
*TG_FT_Biodiesel_MW_25              .  Biodiesel
*TG_FT_Biodiesel_MW_30              .  Biodiesel
*TG_FT_Biodiesel_MW_35              .  Biodiesel
*TG_FT_Biodiesel_MW_40              .  Biodiesel
*TG_FT_Biodiesel_MW_45              .  Biodiesel
*TG_FT_Biodiesel_MW_50              .  Biodiesel

TG_FT_Biodiesel_ST_20              .  Biodiesel
TG_FT_Biodiesel_ST_25              .  Biodiesel
TG_FT_Biodiesel_ST_30              .  Biodiesel
TG_FT_Biodiesel_ST_35              .  Biodiesel
TG_FT_Biodiesel_ST_40              .  Biodiesel
TG_FT_Biodiesel_ST_45              .  Biodiesel
TG_FT_Biodiesel_ST_50              .  Biodiesel

TG_FT_Biodiesel_WO_20              .  Biodiesel
TG_FT_Biodiesel_WO_25              .  Biodiesel
TG_FT_Biodiesel_WO_30              .  Biodiesel
TG_FT_Biodiesel_WO_35              .  Biodiesel
TG_FT_Biodiesel_WO_40              .  Biodiesel
TG_FT_Biodiesel_WO_45              .  Biodiesel
TG_FT_Biodiesel_WO_50              .  Biodiesel

TG_FT_Biodiesel_WP_20              .  Biodiesel
TG_FT_Biodiesel_WP_25              .  Biodiesel
TG_FT_Biodiesel_WP_30              .  Biodiesel
TG_FT_Biodiesel_WP_35              .  Biodiesel
TG_FT_Biodiesel_WP_40              .  Biodiesel
TG_FT_Biodiesel_WP_45              .  Biodiesel
TG_FT_Biodiesel_WP_50              .  Biodiesel

Biodiesel_FT_SUM                   .  Biodiesel


HTL_ST_20                          .  BioOil
HTL_ST_25                          .  BioOil
HTL_ST_30                          .  BioOil
HTL_ST_35                          .  BioOil
HTL_ST_40                          .  BioOil
HTL_ST_45                          .  BioOil
HTL_ST_50                          .  BioOil

HTL_WO_20                          .  BioOil
HTL_WO_25                          .  BioOil
HTL_WO_30                          .  BioOil
HTL_WO_35                          .  BioOil
HTL_WO_40                          .  BioOil
HTL_WO_45                          .  BioOil
HTL_WO_50                          .  BioOil

HTL_WP_20                          .  BioOil
HTL_WP_25                          .  BioOil
HTL_WP_30                          .  BioOil
HTL_WP_35                          .  BioOil
HTL_WP_40                          .  BioOil
HTL_WP_45                          .  BioOil
HTL_WP_50                          .  BioOil

BioOil_SUM                         .  BioOil



*pre-biogas-mix		
Straw_pre_BG_20	.	Pre-process-BG
Straw_pre_BG_25	.	Pre-process-BG
Straw_pre_BG_30	.	Pre-process-BG
Straw_pre_BG_35	.	Pre-process-BG
Straw_pre_BG_40	.	Pre-process-BG
Straw_pre_BG_45	.	Pre-process-BG
Straw_pre_BG_50	.	Pre-process-BG
		
Deep_Litter_pre_BG_20	.	Pre-process-BG
Deep_Litter_pre_BG_25	.	Pre-process-BG
Deep_Litter_pre_BG_30	.	Pre-process-BG
Deep_Litter_pre_BG_35	.	Pre-process-BG
Deep_Litter_pre_BG_40	.	Pre-process-BG
Deep_Litter_pre_BG_45	.	Pre-process-BG
Deep_Litter_pre_BG_50	.	Pre-process-BG
		
Food_Waste_pre_BG_20	.	Pre-process-BG
Food_Waste_pre_BG_25	.	Pre-process-BG
Food_Waste_pre_BG_30	.	Pre-process-BG
Food_Waste_pre_BG_35	.	Pre-process-BG
Food_Waste_pre_BG_40	.	Pre-process-BG
Food_Waste_pre_BG_45	.	Pre-process-BG
Food_Waste_pre_BG_50	.	Pre-process-BG
		
Nature_Area_pre_BG_20	.	Pre-process-BG
Nature_Area_pre_BG_25	.	Pre-process-BG
Nature_Area_pre_BG_30	.	Pre-process-BG
Nature_Area_pre_BG_35	.	Pre-process-BG
Nature_Area_pre_BG_40	.	Pre-process-BG
Nature_Area_pre_BG_45	.	Pre-process-BG
Nature_Area_pre_BG_50	.	Pre-process-BG
		
Manure_tank_20	.	Pre-process-BG
Manure_tank_25	.	Pre-process-BG
Manure_tank_30	.	Pre-process-BG
Manure_tank_35	.	Pre-process-BG
Manure_tank_40	.	Pre-process-BG
Manure_tank_45	.	Pre-process-BG
Manure_tank_50	.	Pre-process-BG



BioGasoline_SUM                    .  Biogasoline





Wood_Mass                          .  Wood
Straw_Mass                         .  Straw
Muni_Waste_Mass                    .  Muni_Waste
Wood_Pellets_Mass                  .  Wood_Pellets
Manure_Mass                        .  Manure
Deep_Litter_Mass                   .  Deep_Litter
Food_Waste_Mass                    .  Food_Waste
Nature_Area_Mass                   .  Nature_Area



Heat_Opti_to_Bal_Conv              .  Excess_Heat_OptiFlow



Other_Gas_Proc                    .   OtherGas




/;



