
SET PROCTECHTYPE(IPROCFROM,TECHTYPE)
/
BioJet_50_ST                       .  BioJet
BioJet_50_WO                       .  BioJet
BioJet_50_WP                       .  BioJet
BioJet_50_ST_H2                    .  BioJet
BioJet_50_WO_H2                    .  BioJet
BioJet_50_WP_H2                    .  BioJet
BioJet_SUM                         .  BioJet
Ethanol_50                         .  Ethanol
Methane_synthesis_TG_50            .  Methane_synthesis
Methanol_synthesis_TG_50           .  Methanol_synthesis
TG_50_MW                           .  Gasifier
TG_50_ST                           .  Gasifier
TG_50_WO                           .  Gasifier
TG_50_WP                           .  Gasifier
BIO_TG_GRID_IN                     .  Gasifier
*TG_FT_Biodiesel_50_MW              .  Biodiesel
TG_FT_Biodiesel_50_ST              .  Biodiesel
TG_FT_Biodiesel_50_WO              .  Biodiesel
TG_FT_Biodiesel_50_WP              .  Biodiesel
Biodiesel_FT_SUM                   .  Biodiesel
ThermGasific_SNG_50_MW             .  SNG
ThermGasific_SNG_50_ST             .  SNG
ThermGasific_SNG_50_WO             .  SNG
ThermGasific_SNG_50_WP             .  SNG
BIO_SNG_OUT                        .  SNG
ThermGasific_SYNGAS_50_MW          .  SYNGAS
ThermGasific_SYNGAS_50_ST          .  SYNGAS
ThermGasific_SYNGAS_50_WO          .  SYNGAS
ThermGasific_SYNGAS_50_WP          .  SYNGAS
BIO_SYNGAS_GRID_OUT                .  SYNGAS
HTL_50_ST                          .  BioOil
HTL_50_WO                          .  BioOil
HTL_50_WP                          .  BioOil
BioOil_SUM                         .  BioOil  



*pre-biogas-mix
Straw_pre_BG                       .  Pre-process-BG
Deep_Litter_pre_BG                 .  Pre-process-BG
Food_Waste_pre_BG                  .  Pre-process-BG
Nature_Area_pre_BG                 .  Pre-process-BG


*BiogasProd_single                  .  Biogas
BiogasProd_mix                     .  Biogas
Biogas_Grid_OUT                    .  Biogas

BiogasUpgr_BMETH_50                .  BiogasUpgr
Methanisation_Bio_BioGas           .  Methanation_Biogas


BioGasoline_SUM                    .  Biogasoline



Electrolysis_H2Prod                .  Hydrogen



Wood_Mass                          .  Wood
Straw_Mass                         .  Straw
Muni_Waste_Mass                    .  Muni_Waste
Wood_Pellets_Mass                  .  Wood_Pellets
Manure_Mass                        .  Manure
Deep_Litter_Mass                   .  Deep_Litter
Food_Waste_Mass                    .  Food_Waste
Nature_Area_Mass                   .  Nature_Area



Heat_Opti_to_Bal_Conv              .  Excess_Heat_OptiFlow



Other_Gas_Proc                    .   OtherGas




/;



