SET S(SSS)  'Seasons in the simulation'                                                        
/                                                                                              
*S01                                                                                           
S26                                                                                
/;                                                                                             
