*Individual users addon

PARAMETER INDIVUSERS_MINSHARE_DH(YYY,RRR,INDIVUSERS_GROUP) 'Minimum share of heat demand in an individual user group (-)';
PARAMETER INDIVUSERS_MAXSHARE_DH(YYY,RRR,INDIVUSERS_GROUP) 'Maximum share of heat demand in an individual user group (-)';
PARAMETER INDIVUSERS_GROUPSHARE(YYY,RRR,INDIVUSERS_GROUP)  'Share of heat demand in an individual user group to be used in future runs (-)'  ;


