
TABLE AGKNDISCDATA(GGG,AGKNDISCSIZES,AGKNDISCDATASET) 'Technology investment data for discrete capacity size investments'

                        AGKNDISCSIZE     AGKNDISCINVCOST     AGKNDISCGOMFCOST
*                           MW                MMoney            kMoney/MW
backstop.AGKNDISCSIZE1     6000                 - 30
backstop.AGKNDISCSIZE2    12000                 - 50
backstop.AGKNDISCSIZE3    18000                - 100
 ;

/*
  600
 1000
 2000

*/