Parameter sav_WNDFLH(AAA) 'Saved data: WNDFLH';
sav_WNDFLH(IA)=WNDFLH(IA);

Parameter sav_SOLEFLH(AAA) 'Saved data: SOLEFLH';
sav_SOLEFLH(IA)=SOLEFLH(IA);

Parameter sav_SOLHFLH(AAA) 'Saved data: SOLHFLH';
sav_SOLHFLH(IA)=SOLHFLH(IA);

Parameter sav_WTRRSFLH(AAA) 'Saved data: WTRRSFLH';
sav_WTRRSFLH(IA)=WTRRSFLH(IA);

Parameter sav_IHYINF_S(AAA,SSS) 'Saved data: IHYINF_S';
sav_IHYINF_S(IA,S)=IHYINF_S(IA,S);

Parameter sav_FUELPRICE(YYY,AAA,FFF) 'Saved data: FUELPRICE';
sav_FUELPRICE(Y,IA,FFF)=FUELPRICE(Y,IA,FFF);

Parameter sav_IXKRATE(IRRRE,IRRRI,S,T) 'Saved data: IXKRATE';
sav_IXKRATE(IRE,IRI,S,T)=IXKRATE(IRE,IRI,S,T);

Parameter sav_GINVCOST(AAA,GGG) 'Saved data: GINVCOST';
sav_GINVCOST(IA,G)=GINVCOST(IA,G);

Parameter sav_IGMAXF(YYY,CCCRRRAAA,FFF) 'Saved data:IGMAXF_Y';
sav_IGMAXF(IY411,C,FFF)=IGMAXF(IY411,C,FFF);

Scalar sav_DISCOUNTRATE 'Saved data:DISCOUNTRATE';
sav_DISCOUNTRATE=DISCOUNTRATE;

*Parameter sav_DE(YYY,RRR) 'Saved data:DE';
*sav_DE(Y,IR)=DE(Y,IR);

*Parameter sav_DH(YYY,AAA) 'Saved data:DH';
*sav_DH(Y,IA)=DH(Y,IA);

Parameter sav_M_POL(YYY,MPOLSET,CCC) 'Saved data:M_POL';
sav_M_POL(Y,MPOLSET,C)=M_POL(Y,MPOLSET,C);

Parameter sav_FUELPRICE(YYY,AAA,FFF) 'Saved data:FUELPRICE';
sav_FUELPRICE(Y,IA,FFF)=FUELPRICE(Y,IA,FFF);

Parameter sav_GKFX(YYY,AAA,GGG) 'Saved data:generation capacity';
sav_GKFX(Y,IA,G)=GKFX(Y,IA,G);


