$ifi %GAS%==yes QCONSUMPTION
QEEQ
*----------------QESTOLOADT
QESTOVOLT
*QGCBGBPR
*QGCBGEXT
*QGCVGEXT
*QGE2LEVEL
$ifi %GAS%==yes QGEQ
*QGGETOH
$ifi %GAS%==yes QGSFXW
$ifi %GAS%==yes QGSVERIGE
*QHEQ
*QHSTOLOADT
*QHSTOVOLT
*----------QHYFXRW
QOBJ
$ifi %GAS%==yes QStoreExt
$ifi %GAS%==yes QStoreInj
$ifi %GAS%==yes QTransEntryCap
$ifi %GAS%==yes QTransExitCap
QXK
VDHF_T
$ifi %GAS%==yes VEXP
$ifi %GAS%==yes VEXT
*VGE2LEVEL
VGE_T
VGH_T
VDEF_T
VDHF_T
$ifi %GAS%==yes VGUD

*VHSTOLOADT
VESTOLOADT
*VHSTOVOLT
VESTOVOLT

$ifi %GAS%==yes VINJ
VOBJ
VQEEQ
*VQHEQ
*VQHSTOVOLT
$ifi %GAS%==yes VSUP
$ifi %GAS%==yes VTC_EN_D
$ifi %GAS%==yes VTC_EN_W
$ifi %GAS%==yes VTC_EX_D
$ifi %GAS%==yes VTC_EX_W
$ifi %X3V%==yes VX3VEX_T
$ifi %X3V%==yes VX3VIM_T
VX_T
$ifi %CAES%==yes VCAESCOMPRESS
$ifi %CAES%==yes VCAESSTORAGE
$ifi %CAES%==yes VCAESWITHDRAW
$ifi %CAES%==yes QCAESBalance
$ifi %CAES%==yes QCAESWithdraw

$ifi %flowbased%==yes  VFBNEX
$ifi %flowbased%==yes  fbline
$ifi %flowbased%==yes  fbhub
$ifi %flowbased%==yes  QFBNEX
$ifi %flowbased%==yes  fbram
$ifi %flowbased%==yes  QFBLIM
$ifi %flowbased%==yes  fbptdf_var_t
$ifi %flowbased%==yes  vx_t
$ifi %flowbased%==yes  xkini

$ONTEXT
VXMAINTVAR
xmaintq
xmaintt
VUCONMAINTbb12
vucon
QXMAINTLIM
$OFFTEXT
;
