* Location of AGKN additions used in add-ons

$ifi %INDUSTRY%==yes       $include   "../../base/addons/industry/bb4/industry_agknadditions.inc";
$ifi %INDIVUSERS%==yes       $include   "../../base/addons/indivusers/bb4/indivusers_agknadditions.inc";
$ifi %OFFSHOREGRID%==yes  $include   "../../base/addons/offshoregrid/bb4/offshoregrid_agknadditions.inc";
$ifi %CCS%==yes  $include   "../../base/addons/CCS/bb4/CCS_agknadditions.inc";
$ifi %HYDROGEN%==yes  $include   "../../base/addons/hydrogen/bb4/hydrogen_agknadditions.inc";
$ifi %DATACENTERS%==yes       $include   "../../base/addons/datacenters/bb4/datacenters_agknadditions.inc";






