* Location of CCCRRRAAA additions used in add-ons

$ifi %OFFSHOREGRID%==yes    $include   "../../base/addons/offshoregrid/bb4/offshoregrid_cccrrraaaadditions.inc";
$ifi %INDUSTRY%==yes        $include   "../../base/addons/industry/bb4/industry_cccrrraaaadditions.inc";
$ifi %INDIVUSERS%==yes      $include   "../../base/addons/indivusers/bb4/indivusers_cccrrraaaadditions.inc";
$ifi %DATACENTERS%==yes     $include    "../../base/addons/datacenters/bb4/datacenters_cccrrraaaadditions.inc";
