

$ifi %COMBTECH%==yes  $include   "../../base/addons/combtech/bb4/combtech_gadditions.inc";
$ifi %INDUSTRY%==yes       $include   "../../base/addons/industry/bb4/industry_gadditions.inc";
$ifi %INDIVUSERS%==yes       $include   "../../base/addons/indivusers/bb4/indivusers_gadditions.inc";
$ifi %HYDROGEN%==yes  $include   "../../base/addons/hydrogen/bb4/hydrogen_gadditions.inc";
$ifi %DATACENTERS%==yes     $include    "../../base/addons/datacenters/bb4/datacenters_gadditions.inc";


