

$ifi %COMBTECH%==yes  $include   "../../base/addons/combtech/bb4/combtech_gggadditions.inc";
$ifi %INDUSTRY%==yes       $include   "../../base/addons/industry/bb4/industry_gggadditions.inc";
$ifi %INDIVUSERS%==yes       $include   "../../base/addons/indivusers/bb4/indivusers_gggadditions.inc";
$ifi %HYDROGEN%==yes  $include   "../../base/addons/hydrogen/bb4/hydrogen_gggadditions.inc";
$ifi %DATACENTERS%==yes     $include   "../../base/addons/datacenters/bb4/datacenters_gggadditions.inc";


