* Latest revision 20171023(hr)

$ifi %testbb1234%==yes            $include "../../base/addons/bb1234compare/bb1234_vardeclare.inc";
$ifi %FLOWBASED%==yes  $include   "../../base/addons/flowbased/flowbased_vardeclare.inc";
$ifi %HYRSBB123%==quantprice      $include "../../base/addons/hyrsbb123/hyrsbb123variables.inc";
$ifi %dflexquant%==yes            $include "../../base/addons/demandflexquant/dflexquant_vardeclare.inc";
