
* This file not used - but similar declarations are used.

SET AGKNDISCAG(AAA,G)   'Areas for possible location of discrete capacity investments in technologies';

SET AGKNDISCGSIZESET    'Set of possible sizes for discrete capacity investments in technologies';

SET AGKNDISCGDATASET    'Technology investment data types for discrete capacity size investments';

PARAMETER AGKNDISCGDATA(GGG,AGKNDISCGSIZESET,AGKNDISCGDATASET) 'Technology investment data for discrete capacity size investments'
