*Offshore grid add-on. Implemented by Juan Gea Bermudez 2019

PARAMETER GINVCOST_ES(GGG,XES) 'Investment cost in hubs at the beginning of each XES (Mmoney)';
PARAMETER GKN_ES(GGG,XES) 'Installed capacity in hubs at the beginning of each XES (MW)';

PARAMETER XINVCOST_ES(YYY,IRRRE,IRRRI,XES) 'Investment cost in transmission lines at the beginning of each XES (money/XKN_ES )';
PARAMETER XKN_ES(IRRRE,IRRRI,XES) 'Installed capacity in transmission lines at the beginning of each XES (MW)';




