* Transport add-on. Added by Juan Gea Bermudez

PARAMETER TRANSDEMAND_Y(YYY,CCC) 'Transport demand per country and year (MWh)';
PARAMETER TRANSDEMAND_S(YYY,CCC,SSS) 'Transport demand per country, year, and season (MWh)  to be used in future runs';
SCALAR TRANS_PEAKAVG_RATIO     'Peak to average ratio for demand related to other transport';
PARAMETER TRANSDEMAND_T_MAX(Y,RRR)   'Maximum power demand (MW) to be used in future runs';


